### ISSUE TITLE
Initial Observations and Questions

### ISSUE THREAD

**Issue by GizmoGoody** [asishrs/smartthings-ringalarmv2#1]
First off, thank you for your work on this. I keep hoping that Ring will open its API and allow this functionality to happen securely with SmartThings (or at a minimum with Alexa). In the meantime your DTH and SmartApp is a great solution, especially as you start to add the security devices.

I was able to follow your v1 to v2 upgrade instructions and it worked without a problem:

Here are my initial observations and questions:

1. I can see my motion sensor, contact sensors, keypad, and range extender, but they do not have labels to tell them apart.
2. Is there a way to make each sensor a unique thing to be used in Automations?
3. The polling interval setting is a good addition, but what exactly is this controlling? For example, if I open a contact sensor, could it be as long as a minute (when set to 1) before its status in ST changes or is there a way to force an update when the sensor's state changes?
4. Where can I see the increased AWS traffic that will eventually result in higher charges?

Thanks again!

**Comment by asishrs** [comment]
1. I am using the device icons to distinguish motion vs contact sensor. All the events based on the devices contains the device name., you can see those in `Recently` tab of app. It is possible to add the device names or add those as child devices (that answers your second question) but I did have enough time do that. I believe the API returns all data points for this. If you or anyone can help in updating the SmartDevice handler, I can accept that change ☺️ 
2. See above
3. The polling interval is kind of delay between the sync with Ring Alarm. In the earlier version, it was `5 minutes` and I received few requests to make that configurable. Unfortunately, there is no way to `force update` as we are using a polling mechanism with APIs in ST.
4. You should be able to check the AWS traffic by visiting 

- https://console.aws.amazon.com/apigateway/home?region=us-east-1#/apis
- Click on your API on the left hand side
- Click on Dashboard

Additionally, you can check the bill here https://console.aws.amazon.com/billing/home?region=us-east-1#/ (you may need to change the region)

**Comment by GizmoGoody** [comment]
Thank you.

1. If I knew what I was doing, I'd be happy to program those names as child devices, but I don't know where to start.
3. Gotcha, thanks.
4. Thanks. I'm interested to see if I can stay in the free tier.

**Comment by asishrs** [comment]
Based on my analysis you will be able to stay on free tier with this app, but it depends on how many other services you are running using the free line as well. If you're concerned about that adjust the polling interval accordingly.

**Comment by GizmoGoody** [comment]
I appreciate all of your work on this so far and any work you're considering to add the children DTH.

**Comment by adessmith** [comment]
I noticed ring has added locks to the system, but they don't seem to show up in the ring DTH like the other devices. This would be awesome if eventually a child DTH could be added for the locks. I'd love to be able to link my locks to ring but have them controllable from smartthings as well.

**Comment by asishrs** [comment]
If you can share the device type details from /meta api, I can add support for the device.

**Comment by adessmith** [comment]
> If you can share the device type details from /meta api, I can add support for the device.

I'm pretty new at this... I would like to help but unfortunately I don't know where to find /meta api... 

Also, I've noticed a strange behavior... I'm not sure if this is functioning correctly but I figured I'd ask just to make sure. Apparently (at least with my implementation) the app will change the alarm state based on the ST home state, but it will not do the reverse. For instance, if I set ST to night mode, it automatically arms my alarm in home mode, however, if I wake up the next morning and disarm ring using the ring keypad, ST never changes back to home mode (yesterday my wife was home all day and I noticed ST was still in nightime mode 4 hours after disarming the ring alarm).
I'm not sure if this is by design, or if the syncing of home modes and alarm states is supposed to be 2-way.

**Comment by asishrs** [comment]
yes, that is a limitation on the current system. you can set that using WebCoRE.

**Comment by adessmith** [comment]
I'm pretty new to smartthings. I have installed WebCore, but I've never created a piston.
Is there an example piston somewhere that changes the home mode based on the ring alarm state?

**Comment by asishrs** [comment]
I don't have one this use case, you can refer a sample here https://github.com/asishrs/smartthings-ringalarmv2#integration-with-webcore

**Comment by javier-jm** [comment]
Hi asishrs,

First of all thank you for all the great work here! I'm interested on making each sensor it's own thing but need some guidance.

You mentioned the API already returns everything needed. I am just wondering if I create a new device type and perform the API calls is there any way we could share the same API call amongst all the devices? Or would we always be making an API call per device (potentially making this very expensive)?

**Comment by javier-jm** [comment]
After spending some time reading the SmartThings documentation I have this working:

https://github.com/javier-jm/smartthings

I basically added the ability to create the motion/contact sensors as children devices. This allows using them as "Things" in automation tasks. Still on very early development, let me know what you think.

**Comment by asishrs** [comment]
@javier-jm excited with this. I will check this soon.

**Comment by schpeen** [comment]
> Hi asishrs,
> 
> First of all thank you for all the great work here! I'm interested on making each sensor it's own thing but need some guidance.
> 
> You mentioned the API already returns everything needed. I am just wondering if I create a new device type and perform the API calls is there any way we could share the same API call amongst all the devices? Or would we always be making an API call per device (potentially making this very expensive)?

I see you added the flood/freeze sensors that's awesome and nice work. Any chance of adding the Ring Panic buttons, and Ring listener as well to view status??

**Comment by schpeen** [comment]
> After spending some time reading the SmartThings documentation I have this working:
> 
> https://github.com/javier-jm/smartthings
> 
> I basically added the ability to create the motion/contact sensors as children devices. This allows using them as "Things" in automation tasks. Still on very early development, let me know what you think.

I see you added the flood/freeze sensors that's awesome and nice work. Any chance of adding the Ring Panic buttons, and Ring listener as well to view status??

**Comment by javier-jm** [comment]
Everything coming from the /status API can be added (not sure if panic
button is being reported right now). However if it is be mindful that right
now the polling time is 1 minute and not sure if that defeats the purpose
of a panic button to begin with.

I'm thinking on creating a shorter polling time (every X seconds instead)
for people willing to pay a bit more of the API usage/lambda (or hosting
their own mini server in a raspberry PI for example). Will look into this
two things later this month when I have time to code again.

**Comment by mropincar** [comment]
Any chance you added the Freeze functionality to the flood freeze sensor? I see that it reports wet or dry but not frozen.

**Comment by asishrs** [comment]
This integration is old and not tested with new ST application. I am not having time to work on this now. If someone can figure this out and send a pull request, I am happy to review that.
