### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by Yooshaw** [asishrs/smartthings-ringalarmv2#10]
I'm having problems getting this to work.  When I try to test, I get this:

![image](https://user-images.githubusercontent.com/43063206/56462635-3ce93b00-638c-11e9-9d2c-f5a81577fe7d.png)

![image](https://user-images.githubusercontent.com/43063206/56462639-52f6fb80-638c-11e9-8db0-5975a0044d8e.png)

I'm getting nothing in the classic smartthings app - looks like it isn't connecting.

**Comment by Yooshaw** [comment]
Any help?

**Comment by asishrs** [comment]
can you check the logs in the cloud watch and see if you get more specific details

**Comment by Its2loud1** [comment]
Can someone please explain these steps for me?  
Test Lambda
URLs

    POST /{Invoke URL From Above}/meta
    POST /{Invoke URL From Above}/status
    POST /{Invoke URL From Above}/off
    POST /{Invoke URL From Above}/home
    POST /{Invoke URL From Above}/away

Sample meta cURL

Request

  curl -X POST \
    {Invoke URL From Above}/meta \
    -H 'x-api-key: aws_gateway_api_key' \
    -d '{
    "user": "ring username",
    "password" : "ring password"
  }'

Response

{
    "locationId": "your_ring_alarm_locaion_id",
    "zId": "your_ring_alarm_zid"
}

Sample status cURL

Request with locattionId and zid.

Eventhough you can run without locattionIdandzid`, this is the recommended approach as it will save time in the lambda execution

  curl -X POST \
    {Invoke URL From Above}/status \
    -H 'x-api-key: aws_gateway_api_key' \
    -d '{
    "user": "ring username",
    "password" : "ring password",
    "locationId" : "ring location Id",
    "zid" : "ring zid",
    "historyLimit": 10
  }'

Request without locattionId and zid.

  curl -X POST \
    {Invoke URL From Above}/status \
    -H 'x-api-key: aws_gateway_api_key' \
    -d '{
    "user": "ring username",
    "password" : "ring password"
    "historyLimit": 10
  }'


I'm not having any luck testing with any of the preferred methods.  Used Terminal on a mac or anything else. I'm getting this result in Terminal
<img width="514" alt="Screen Shot 2019-05-06 at 10 09 19 AM" src="https://user-images.githubusercontent.com/49612825/57242084-6c808000-6fe7-11e9-8c06-7a1cdd7cab5f.png">

Thanks.

**Comment by diablodayv** [comment]
Did you get anywhere with this?  I am lost on the Test setup part as well and I also don't have a Mac so not sure how to get the location info for the next step either!

**Comment by asishrs** [comment]
> Did you get anywhere with this? I am lost on the Test setup part as well and I also don't have a Mac so not sure how to get the location info for the next step either!

You have couple of options here.

- Use a REST API testing tool like https://www.getpostman.com/
- Use a plugin with your chrome browser like https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo?hl=en-US
For postman, you can refer below screenshots!

<img width="961" alt="Screen Shot 2019-05-10 at 9 01 11 PM" src="https://user-images.githubusercontent.com/12078528/57564912-f7a3a200-7368-11e9-9005-a955a7277b72.png">

<img width="976" alt="Screen Shot 2019-05-10 at 9 02 01 PM" src="https://user-images.githubusercontent.com/12078528/57564915-fe321980-7368-11e9-9965-6f8a50bef29e.png">

**Comment by Its2loud1** [comment]
I finally got it working. I never really got the testing down but was getting the “forbidden” error when I was just putting In the Lamda web address into a browser. I erased everything and started over. I found this post about setting up the Ring Alarm usage plan which I did not see in Asishrs  instructions. That fixed my “forbidden” issue. Hope that helps. 
https://community.smartthings.com/t/ring-alarm-released-integration-project-in-post-13/128449/35?u=its2loud

Asishrs, could you comment on setting up the usage plan.

**Comment by Its2loud1** [comment]
It’s not stale. The issues still exist

**Comment by Jrsmarthome** [comment]
First thanks for the integration work! 

I have a few of issues regarding the installation.
  1) I cannot retrieve the ZID number
       - I tested the Lambda via Postman but and I get a 502- Bad Gateway error. I read somewhere that the error will solve itself, is that true?
       - I attempted the Network Panel via finding Socket.io, but I could not find that specific word under. Any thoughts how to do it?
  2) The Smartthings Classic app does not activate the alarm functions but it knows if I change the status on the Ring App. All sensors are detected and working on Smartthings. 
  3) The newer Smartthings app does not detect the sensor, it just has option for Off and alarm settings

Any help/guidance will be greatly appreciated

**Comment by asishrs** [comment]
> First thanks for the integration work!
> 
> I have a few of issues regarding the installation.
> 
> 1. I cannot retrieve the ZID number
>    
>    * I tested the Lambda via Postman but and I get a 502- Bad Gateway error. I read somewhere that the error will solve itself, is that true?
>    * I attempted the Network Panel via finding Socket.io, but I could not find that specific word under. Any thoughts how to do it?
> 2. The Smartthings Classic app does not activate the alarm functions but it knows if I change the status on the Ring App. All sensors are detected and working on Smartthings.
> 3. The newer Smartthings app does not detect the sensor, it just has option for Off and alarm settings
> 
> Any help/guidance will be greatly appreciated

If you cannot make calls to API, the lambda setup is not working. I am aware that people reported this in the past but it’s hard to debug this issue. Can you keep the current lambda and setup a new one to validate this?

**Comment by asishrs** [comment]
I recommend updating to the latest version.
