### ISSUE TITLE
Arm/Disarm as a switch?

### ISSUE THREAD

**Issue by jaas666** [asishrs/smartthings-ringalarmv2#11]
Any way to make the arming act like a regular switch or some other way to interact with the alarm without using the ST mode?

I need to set up a routine to simply arm at nights since I tend to forget. Sure I can set a routine to change the ST mode thus changing the alarm state, but when I disarm the system at the panel the ST mode doesn't change... So when triggering the routine again nothing happens because ST is already on that mode.

Any suggestion?

**Comment by asishrs** [comment]
You can do that using `Automation` option in ST. There is an option for `Automatically perform 'Good Night' when`
