### ISSUE TITLE
Can't use Ring Alarm devices in Smartthings after updating to V2

### ISSUE THREAD

**Issue by ikillratz** [asishrs/smartthings-ringalarmv2#12]
I updated from V1 to V2.  Under the Ring Alarm item in ST I can see 12 contact sensors and they all show closed.  I can't get the devices though to show in WebCore or any SmartApps in ST.  I would like to be able to perform an action (like turn on a light) when a Ring contact sensor opens.  Does your code allow for that somehow?  None of the Ring devices show up in WebCore as any type of device, other than the Ring Alarm itself.

**Comment by asishrs** [comment]
The code doesn't support this. This is one of the enhancement I am planning.

**Comment by proedgebiker** [comment]
> I updated from V1 to V2. Under the Ring Alarm item in ST I can see 12 contact sensors and they all show closed. I can't get the devices though to show in WebCore or any SmartApps in ST. I would like to be able to perform an action (like turn on a light) when a Ring contact sensor opens. Does your code allow for that somehow? None of the Ring devices show up in WebCore as any type of device, other than the Ring Alarm itself.

This can now be done via the alexa app. Alexa acts like a bridge between the ring alarm and ST to create routines. I was literally in the process of trying to get this working as Ring and Alexa updated this awesomeness. 
![268EA1B6-04DF-4DD5-8A92-B3673335BBAE](https://user-images.githubusercontent.com/35698922/58298848-09df0080-7dab-11e9-8bd7-c5b88cce01bd.jpeg)

**Comment by ikillratz** [comment]
Yeah, I found this out but it isn't the best.  I have 99% of my automation programming in WebCore and it is more complicated then simple one conduction IF conditions. Wish Alexa supported complex/nested IF statements

**Comment by proedgebiker** [comment]
> Yeah, I found this out but it isn't the best. I have 99% of my automation programming in WebCore and it is more complicated then simple one conduction IF conditions. Wish Alexa supported complex/nested IF statements
ok, I was answering by the simple request you posted which this does.
"I would like to be able to perform an action (like turn on a light) when a Ring contact sensor opens"

**Comment by proedgebiker** [comment]
> Yeah, I found this out but it isn't the best. I have 99% of my automation programming in WebCore and it is more complicated then simple one conduction IF conditions. Wish Alexa supported complex/nested IF statements

ok, I was answering by the simple request you posted which this does.
"I would like to be able to perform an action (like turn on a light) when a Ring contact sensor opens"

**Comment by asishrs** [comment]
You can try the latest version of the app and try this.
