### ISSUE TITLE
Alarm sending multiple notifications 

### ISSUE THREAD

**Issue by ikillratz** [asishrs/smartthings-ringalarmv2#13]
I have the Ring SmartApp set to send a text when the alarm changes status.  I get multiple notifications that the alarm changes to Armed Away and Disarmed modes.  Any idea why this is happening?
![Screenshot_20190524-083359_SmartThings](https://user-images.githubusercontent.com/32552753/58328111-49373c80-7dff-11e9-8c09-dd3a2471ed58.jpg)

**Comment by asishrs** [comment]
@ikillratz can you update the latest version of the app and test this?
