### ISSUE TITLE
Error on SmartApp Install

### ISSUE THREAD

**Issue by richleyh** [asishrs/smartthings-ringalarmv2#14]

**Comment by richleyh** [comment]
Hello! First, thank you for all of your work with this! I am a complete novice, but I've slogged my way through most of this. I'm stuck on installing the SmartApp, of all things, usually quite an easy process. I get the following error:

groovy.lang.MissingPropertyException: No such property: id for class: java.lang.String

   I have tried re-pasting the code multiple times. Others have used it successfully, so I'm certain it isn't a flaw in the code itself, but rather and error somewhere else in my install process.
    
   The only other hiccup in my install process has been a 502:Bad Gateway error when testing using the "/status" suffix. When using the /meta, /off, /home, etc., they all seem to work. Wondering if there might be a connection to the "/status" fail and the error generated when I attempt to install the SmartApp? ?Thanks in advance for any help you might be able to offer!

<img width="809" alt="Screen Shot 2019-05-25 at 6 28 53 PM" src="https://user-images.githubusercontent.com/49592858/58375548-331e9e80-7f1b-11e9-961e-05bac98ed24a.png">

<img width="2558" alt="Screen Shot 2019-05-25 at 6 23 07 PM" src="https://user-images.githubusercontent.com/49592858/58375511-29e10200-7f1a-11e9-97fc-37388d75a057.png">

**Comment by ikillratz** [comment]
I get the same issue when I install the smartapp.  I am still able to publish the code though and install the smartapp in the SmartThings app but the stats of the Ring Alarm never communicates between Ring and Smartthings.  I have all the devices showing properly show.  I just can't automate the alarm changing status.

**Comment by asishrs** [comment]
I tried to simplify the installation process in the latest version. can you try that?
