### ISSUE TITLE
Alarm not changing status

### ISSUE THREAD

**Issue by ikillratz** [asishrs/smartthings-ringalarmv2#16]
I removed the V1 of the integration and started from scratch with the V2 integration.  I have the Ring Alarm device in my devices in Smartthings along with all my sensors.  They appear to be showing properly.  However, I can not get the alarm status to talk between smartthings and the Ring Alarm itself.  When I set the Smartthings Ring Alarm device to home.  It shows it is set to home but then about 5 seconds later it shows it is disarmed.  Also, the actual Ring Alarm never changed to the home mode.  It was disarmed to start with and it stayed disarmed the whole time.  I also have the SmartApp set to change the location mode in Smartthings when the alarm changes status.  That doesn't work either.  So I have the devices showing but the status doesn't communicate between Smartthings and the alarm.  When I got to the Ring app and change the alarm status nothing triggered in Smartthings also.

**Comment by ikillratz** [comment]
I forgot to mention I got this error when trying to install the SmartApp

groovy.lang.MissingPropertyException: No such property: id for class: java.lang.String

I got that when I tried to save the code.  I am not sure what is causing the issue and how to fix it.

**Comment by asishrs** [comment]
Do you still see the issue ?

**Comment by ikillratz** [comment]
I removed the smartapp after trying to set it up about 5 times.  Last time I tried it I was still getting the errors.

**Comment by DMaverock** [comment]
For me it only syncs from Ring to SmartThings and not the other way around. If I change the status of the Ring Alarm in the Ring App, I can see those changes in the SmartThings Ring Alarm device. Changing the status of the SmartThings Ring Alarm device does nothing to the actual Ring Alarm and I get the same behavior as the OP where after a few seconds the SmartThings Ring Alarm status will change back to disarmed.

**Comment by BubblesOnBrain** [comment]
I am having these issues as well.  I tested sending an away call outside of the lambda function and it is not setting the alarm to away (or any other status).  Strange though, I thought this was working several days ago.    I get a message success back from the lambda-api call but no go on switching the alarm status.   Is their Ring API documentation or is this all being reverse engineered?  Thanks for all the work on this!

**Comment by alijaf123** [comment]
> For me it only syncs from Ring to SmartThings and not the other way around. If I change the status of the Ring Alarm in the Ring App, I can see those changes in the SmartThings Ring Alarm device. Changing the status of the SmartThings Ring Alarm device does nothing to the actual Ri

I am having the exact same issue.

**Comment by asishrs** [comment]
@JoKohl https://github.com/asishrs/smartthings-ringalarmv2/issues/16#issuecomment-522360265 Unfortunately, there is no documentation on the API part. You can go through the code to for this. 

It's working on my ST app, keep in mind that the status takes time to reflect on the ST app. You can adjust that using the `Polling Interval` in ST app.

**Comment by asishrs** [comment]
> For me it only syncs from Ring to SmartThings and not the other way around. If I change the status of the Ring Alarm in the Ring App, I can see those changes in the SmartThings Ring Alarm device. Changing the status of the SmartThings Ring Alarm device does nothing to the actual Ring Alarm and I get the same behavior as the OP where after a few seconds the SmartThings Ring Alarm status will change back to disarmed.

Can you check the apis working as expected?

**Comment by adessmith** [comment]
I see this was closed... did anyone here ever get it working properly? I've been having the same issue and I don't see a resolution here.

**Comment by DMaverock** [comment]
To be honest I switched to Home Assistant and connected it with Ring. Then I connected SmartThings and HA and created a SmartThings button "RingArmAway" and "RingArmHome" that would trigger HA to arm Ring. Has been working for 6 months now without issue
