### ISSUE TITLE
Can anyone help me with this error message I see in the live logging of ST?

### ISSUE THREAD

**Issue by Its2loud1** [asishrs/smartthings-ringalarmv2#18]
![D67F8E50-EB6D-4E21-AABA-D7C1DE5003BC](https://user-images.githubusercontent.com/49612825/63949782-c17d5180-ca2f-11e9-8c58-cb8fb39975ce.jpeg)

**Comment by Its2loud1** [comment]
I rebuilt my Lambda and API's and I'm still not getting any sensor info in the SmartThings app as seen in the picture.  I can arm and disarm in the ST app but when I arm or disarm from the Ring app, the ST app does not update.  This once worked for me. 

I can't figure out what the problem is and it's really frustrating.  Any help would be greatly appreciated and I'll happily donate for the time spent. 
![IMG_FA9F4036A906-1](https://user-images.githubusercontent.com/49612825/65658178-6b261300-dfdb-11e9-9c08-f8a26e11bda9.jpeg)

**Comment by Its2loud1** [comment]
I believe there is something definitely wrong with the polling between ST and Ring Alarm with this integration.  I setup a completely new Lambda and API's under a new east coast AWS (ohio) and I'm still not getting any feedback from Ring in ST in regards to sensors, keypads, or even base station.  The only thing I can do is Arm Away, Disarm, and Arm Home.  It would really be great if there was some support for this.  It's possible I'm still missing something in the AWS setup but I've done it maybe 6 times, following each step carefully with the same end results. I've triple checked my location ID and ZID and both are correct.

**Comment by asishrs** [comment]
Can you confirm you installed the version 2 - https://github.com/asishrs/smartthings-ringalarmv2 ? 

Also, can you check the `/status` api from a `curl` or `postman` and see you are able see `events` on the response?

**Comment by Its2loud1** [comment]
![9CAEB7BE-7E37-489F-BD58-91ED52EFCF57](https://user-images.githubusercontent.com/49612825/65834730-9773b500-e2a3-11e9-859f-07379e527c39.jpeg)
I can confirm I used v2

Here is the curl response

**Comment by asishrs** [comment]
This is saying that you haven't set the correct authentication token. Can you pass the auth token along with the request as mentioned here https://github.com/asishrs/smartthings-ringalarmv2#sample-status-curl

**Comment by Its2loud1** [comment]
I will check again but I’m pretty sure I have the correct token.  I will quadruple check. 

Thanks.

**Comment by Its2loud1** [comment]
Just to confirm. I am using the API key given to me in this step. 

From the API main page, select API Keys
Select your API Key
Click on Show link on the API key
Save API Key for SmartThings Application configuration.

**Comment by Its2loud1** [comment]
This is what I'm putting into Terminal on my mac and everything I've I get this response.  

I do not know what I'm doing wrong and I've had this working months ago. 

<img width="586" alt="Screen Shot 2019-10-01 at 9 23 17 PM" src="https://user-images.githubusercontent.com/49612825/66018018-28a87e80-e492-11e9-949a-202ed6653987.png">

**Comment by Its2loud1** [comment]
ok.  I have checked and rechecked my API key.  It is not wrong. Something is not working right and I can't figure out what it is.  Any help here would be appreciated.

**Comment by asishrs** [comment]
> This is what I'm putting into Terminal on my mac and everything I've I get this response.
> 
> I do not know what I'm doing wrong and I've had this working months ago.
> 
> <img alt="Screen Shot 2019-10-01 at 9 23 17 PM" width="586" src="https://user-images.githubusercontent.com/49612825/66018018-28a87e80-e492-11e9-949a-202ed6653987.png">

you have an extra `}` after `default`as part of the url. Remove that and try

**Comment by Its2loud1** [comment]
ok. I'm not sure i understand then because I'm using your example on your Github exactly how you typed it only replacing the URL with the actual URL and the API KEY, Username and Password

curl -X POST \
    {Invoke URL From Above}/meta \
    -H 'x-api-key: aws_gateway_api_key' \
    -d '{
    "user": "ring username",
    "password" : "ring password"
  }'




curl -X POST \
    https://q77ngzehje.execute-api.us-east-1.amazonaws.com/default/meta \
    -H 'x-api-key: 4tgfSadaRF3XzNpZ5aaBN7072925Xw9X6sVIRe48' \
    -d '{
    "user": “xxxx@xxxxxx.com”,
    "password" : “xxxxxoud1!”
  }'


and I'm getting the same response.  
<img width="493" alt="Screen Shot 2019-10-21 at 9 07 45 PM" src="https://user-images.githubusercontent.com/49612825/67258768-15f8e800-f447-11e9-9ded-5d10a03dbf7b.png">
