### ISSUE TITLE
Two Factor Authentication

### ISSUE THREAD

**Issue by GizmoGoody** [asishrs/smartthings-ringalarmv2#19]
@asishrs As we all know, Ring has been in the news a lot lately for "hackers" getting into Ring users' systems due to poor password practices, etc. In any case, Ring recently enabled two-factor authentication, so without really thinking, I turned it on in the Ring app. Now I keep getting the two factor authentication codes (I think) because of the calls from this setup.

Any possibilities of your code working with two factor authentication or do I need to choose (this setup or two factor)?

**Comment by asishrs** [comment]
Thanks for requesting. This is in my TODO list. I have to check the Ring APIs for the support. I will update this issue soon.

**Comment by GizmoGoody** [comment]
Excellent! Thank you. When you do, would you consider pulling the @javier-jm updates in so that I can continue to use the child devices as Things in automations and ActionTiles?

https://github.com/javier-jm/smartthings/blob/SensorsAsThings/devicetypes/javierj/RingAlarmWithSensors.groovy

**Comment by asishrs** [comment]
Yes, in fact I am using @javier-jm version of the app now :) This requires change on both ST app and api side.

Figured the APIs. I will work on this.

**Comment by asishrs** [comment]
API changes are complete, you can check that https://github.com/asishrs/smartthings-ringalarmv2/tree/feature/2fa 
I am facing issues with the ST Device Handler input side. I have created a ticket in ST forum for same https://community.smartthings.com/t/classic-device-handler-large-input/183606

I have hardcoded the token in ST  Device Handler and everything is working as expected with 2FA enabled. Based on the recommendation from the forum, I will update the next steps.

**Comment by GizmoGoody** [comment]
Awesome! Thanks. I’m no programmer, but I did stay at a Holiday Inn Express last night (and know a little Excel). Could you parse the first 400 characters into one text field, then take the rest in another, and concatenate when used later?

I’ve seen your other changes on the API side recently as well. Once you figure out this character limit issue, I think I’ll be updating the Lambda and DTH. Do I have that right? Will I need to reinstall all devices and the SmartApp as well?


________________________________

**Comment by asishrs** [comment]
> Awesome! Thanks. I’m no programmer, but I did stay at a Holiday Inn Express last night (and know a little Excel). Could you parse the first 400 characters into one text field, then take the rest in another, and concatenate when used later? I’ve seen your other changes on the API side recently as well. Once you figure out this character limit issue, I think I’ll be updating the Lambda and DTH. Do I have that right? Will I need to reinstall all devices and the SmartApp as well?
> […](#)

Thanks for the suggestion. I have rewrote the ST app and handler as part of this. In the new version, all the settings are part of the ST app. I am currently testing this.

**Comment by javier-jm** [comment]
@asishrs let me know if you need any help with the ST app side of things.

**Comment by asishrs** [comment]
> @asishrs let me know if you need any help with the ST app side of things.

Thanks @javier-jm ! I just finished the last steps and going to test it for couple of days. The ST app side changes are based on your work 😉 I will find some time over weekend to document this and I need your help in validating.

**Comment by asishrs** [comment]
@javier-jm @GoodyGizmos I have pushed the changes for the new version. This is almost a complete rewrite for simple installation on both AWS side as well as SmartThings. I am running this version on my device for new days and didn't observe anything wrong. Can you help to test this? 

https://github.com/asishrs/smartthings-ringalarmv2
https://github.com/asishrs/smartthings

**Comment by GizmoGoody** [comment]
@asishrs I started the process to rollback and was able to remove all connections to other SmartApps/Integrations except one last webCoRE piston. I'm unable to save changes, delete, or even pause the piston. Very strange. This also appears to be preventing me from removing the Ring Alarm device with this error:

Could not roll back Hibernate transaction; nested exception is org.hibernate.TransactionException: JDBC rollback failed

Can you make anything of that?

Once I'm able to remove all remnants of the previous Integrations, Devices, and DTHs will I need to change anything with the AWS Lambda setup or is that still good with your new code?

Also, should I be installing this new SmartApp through ST Classic or the new app?

**Comment by GizmoGoody** [comment]
@asishrs I tried to finish the old setup cleanup this morning and it worked. Not sure what was going on there. Before I proceed with the new setup, can you please answer the two questions at the end of my last post?

**Comment by asishrs** [comment]
@GoodyGizmos 
> Once I'm able to remove all remnants of the previous Integrations, Devices, and DTHs will I need to change anything with the AWS Lambda setup or is that still good with your new code?

Yes, you need to install the latest version of lambada 1.3.3 and it’s very simple to setup. T

> Also, should I be installing this new SmartApp through ST Classic or the new app?

ST classic app

**Comment by GizmoGoody** [comment]
@asishrs OK, thank you. I start to lose track of what I'm accomplishing every time I look at the AWS Lambda settings and get concerned that I could configure something wrong anytime I mess with it. Can you please clarify exactly which steps are new or modified? Also, should the top of the v3 readme say "v3" instead of "v2?"

**Comment by asishrs** [comment]
You can the whole AWS setup in two steps. Follow the updated instructions.

**Comment by GizmoGoody** [comment]
@asishrs OK, I went through the steps and now see it's an entirely different AWS Lambda setup than before. All of the instructions worked out except 2FA. When I tap "Ring Account Status" the spinning wheel pops up for 1-2 seconds and disappears with no ZID or Location information displayed. Should OAuth be authorized in the SmartApp?

**Comment by Littleaton** [comment]
I am getting the same thing, no code is sent, and ring account status shows nothing.

> @asishrs OK, I went through the steps and now see it's an entirely different AWS Lambda setup than before. All of the instructions worked out except 2FA. When I tap "Ring Account Status" the spinning wheel pops up for 1-2 seconds and disappears with no ZID or Location information displayed. Should OAuth be authorized in the SmartApp?

**Comment by GizmoGoody** [comment]
> I am getting the same thing, no code is sent, and ring account status shows nothing.
> 
I get codes, but nothing appears to happen when I input it and tap the button.

**Comment by asishrs** [comment]
There was an issue in the usage plan setup - by mistake, I used max 2000 calls per month. I fixed it https://github.com/asishrs/smartthings-ringalarmv2/pull/30/commits/25a0545450121f35bf51108997b1788e21254918

You can delete the stack from https://console.aws.amazon.com/cloudformation/home?region=us-east-1 page - Tap on the stack name and click on the delete button  
Or update the usage plan from https://console.aws.amazon.com/apigateway/home?region=us-east-1#/usage-plans page by selecting the `st-ring-alarm-usage-plan` and click edit button then remove the option on `Enable throttling` and `Enable quota`

**Comment by asishrs** [comment]
> > I am getting the same thing, no code is sent, and ring account status shows nothing.
> 
> I get codes, but nothing appears to happen when I input it and tap the button.

Did you tap the `Ring Account Status` or `Done` ?

**Comment by asishrs** [comment]
> I am getting the same thing, no code is sent, and ring account status shows nothing.
> 
> > @asishrs OK, I went through the steps and now see it's an entirely different AWS Lambda setup than before. All of the instructions worked out except 2FA. When I tap "Ring Account Status" the spinning wheel pops up for 1-2 seconds and disappears with no ZID or Location information displayed. Should OAuth be authorized in the SmartApp?

can you check logs for any possible errors?

**Comment by Littleaton** [comment]
>> I am getting the same thing, no code is sent, and ring account status shows nothing. ...

@asishrs how can i test my api from aws i wonder if that is the issue.  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by asishrs** [comment]
> > > I am getting the same thing, no code is sent, and ring account status shows nothing. ...
> 
> @asishrs how can i test my api from aws i wonder if that is the issue.
> 
> Sent with [GitHawk](http://githawk.com)

If you have used the new setup via the cloudformation stack, the only issue will be with the usage plan which can be fixed by following this https://github.com/asishrs/smartthings-ringalarmv2/issues/19#issuecomment-579036781 I was having issues with my setup from today morning and I fixed that following same.

For testing the API, I recommend the below approach.
1. First, test your api using a rest client like Postman, this will help to identify issues at the gateway. You can use the same data as in step 2 in Postman
2. Second, test the api directly in AWS, for that
- Go to https://console.aws.amazon.com/apigateway/home?region=us-east-1#/apis/
- Select your api
- Click **Resources** >> Click **ANY** >> Click **Test** link on the left side
- On the **Method Execution** screen, choose your options as below.
   - Method - `POST`
   - Action - `Status`
   - Headers - `x-api-key:your-aws-api-key`
   -  Request Body - 
```
{
	"user": "your ring email id",
	"password" : "kavalK@6@n",
	"locationId" : "ring location id",
	"zid" : "ring zid",
	"historyLimit": 10
}
```

**Comment by GizmoGoody** [comment]
> > > I am getting the same thing, no code is sent, and ring account status shows nothing.
> > 
> > 
> > I get codes, but nothing appears to happen when I input it and tap the button.
> 
> Did you tap the `Ring Account Status` or `Done` ?

@asishrs I tried both. Neither worked. I've disabled throttling and quota.

Here are a few minutes of Ring Alarm Manager logs
![Capture](https://user-images.githubusercontent.com/46235745/73241407-c1a48900-4156-11ea-9709-97a524ff3665.PNG)

**Comment by asishrs** [comment]
@GoodyGizmos based on the logs, you may have an issue with ring account information. The ring authentication methods invoke the ring APIs not the lambda. Those are failing in your case. 

Also, there was a bug in device handler which prevents the creation of child devices, I fixed it yesterday https://github.com/asishrs/smartthings/commit/435bcd9d94b0a6716c65e04be91ab9ec616b3526 This is unrelated to the issue you are facing.

If you are interested in reading the troubleshooting I did yesterday, you can check https://github.com/asishrs/smartthings/issues/12

**Comment by GizmoGoody** [comment]
@asishrs I’ve confirmed I’m using the correct login information. Are you saying I should double check the API setup based on your instructions?

Now I can’t get the new SmartApp to request a code like I was able to previously. Also, when I try to turn off 2FA in the Ring app, I get this error:
![B8B9A414-85E4-49BD-A84C-8C21F3967077](https://user-images.githubusercontent.com/46235745/73274159-f128b500-4199-11ea-93a8-091e2f67bfc3.jpeg)
This matches lines in the log (too many requests) and I think I’ve deleted traces of your previous AWS and Lambda code, so the only things that should be requesting a code are the new AWS Lambda and Ring app, right?

Any recommendations for next steps?

**Comment by asishrs** [comment]
Yes, this means you have received too many OTP codes and didn’t use those. There is a limit on Ring side on the number of times you can request the code. Are you receiving Ring 2FA codes on the registered phone number while you are trying to setup the app?

The new version of the smart app register your ring account and poll for the updates as well.

For now, I suggest you to remove the app. Wait for to Ring to remove the soft limit they put on the account and try again.

**Comment by GoodyGizmos** [comment]
Not any more

________________________________

**Comment by Littleaton** [comment]
@asishrs  Ok i was able to finally get the 2fa to send the code. I am now going to  "smartthings alarm device" And it is telling me i have no devices of this capability. What am I doing wrong now?

**Comment by asishrs** [comment]
@eatonaaron did you setup the ring device handler?

**Comment by Littleaton** [comment]
> @eatonaaron did you setup the ring device handler?


YEs, what am i missing? 
![Screen Shot 2020-01-28 at 9 01 15 AM](https://user-images.githubusercontent.com/55291686/73281194-d449ad00-41ac-11ea-8cea-9986f7d7f3b6.png)

**Comment by asishrs** [comment]
You need to install the device - https://github.com/asishrs/smartthings/blob/master/README.md#setup-alarm-device

**Comment by Littleaton** [comment]
> You need to install the device - https://github.com/asishrs/smartthings/blob/master/README.md#setup-alarm-device

Duh! Ok thanks! im in and seems to be working. I will mess around and let you know if i find any problems.

**Comment by Littleaton** [comment]
@asishrs  Should The ring alarm manager keep the settings in it? i have closed the smart app and setup some routines, and then later on gone back into it and my api info / ring login info is gone.

**Comment by Littleaton** [comment]
@asishrs  Nevermind, i see what it does. creates a new "smart app" with those settings.

**Comment by Littleaton** [comment]
@asishrs  IS it possible to create a routine that will change the ring alarm mode without changing the shm mode?

I cant seem to do that without only changing the shm mode? Also, the polling setting in the smartapp, IS that polling for new devices, or status/mode changes.  Like if i change the alarm mode in my ring app, will it instantly change it in smartthings? and notify me, or is that part of the polling, it will update smartthings once it polls again?

**Comment by asishrs** [comment]
You can set the Ring Alarm mode change based on ST mode. Check section `4.III.b` on https://github.com/asishrs/smartthings#setup-smartthings-app

**Comment by Littleaton** [comment]
@asishrs  right i understand that, but i do not want to. What if i just want to do the ring mode and leave the ST mode where it is?

Also, do you have any example pistons for webcore? I am new to webcore, never used it. So would love to dive in but need some examples to start with.

For example, changing ring mode based on me leaving in the morning between certain times on weekdays only.

**Comment by asishrs** [comment]
@eatonaaron I am unable to open WebCore UI in the past two days. You can see several examples of the above use cases in WebCore and ST community. I encourage you to check that.

**Comment by Littleaton** [comment]
>@eatonaaron I am unable to open WebCore UI in the past two days. You can see several examples of the above use cases in WebCore and ST community. I encourage you to check that. 

@asishrs ok. i am going to work on adding the other alarm devices if you have not stated already.  and add some additional features to them. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by asishrs** [comment]
> > @eatonaaron I am unable to open WebCore UI in the past two days. You can see several examples of the above use cases in WebCore and ST community. I encourage you to check that.
> 
> @asishrs ok. i am going to work on adding the other alarm devices if you have not stated already. and add some additional features to them.
> 
> Sent with [GitHawk](http://githawk.com)

I have a Smoke/CO Listener, that is in my plan. It will be great if you can open pull requests once you figure out additional devices. Also, you may track that under a different GitHub issue than this.

**Comment by asishrs** [comment]
@eatonaaron check this https://github.com/asishrs/smartthings/issues/16

**Comment by GizmoGoody** [comment]
> Yes, this means you have received too many OTP codes and didn’t use those. There is a limit on Ring side on the number of times you can request the code. Are you receiving Ring 2FA codes on the registered phone number while you are trying to setup the app?
> 
> The new version of the smart app register your ring account and poll for the updates as well.
> 
> For now, I suggest you to remove the app. Wait for to Ring to remove the soft limit they put on the account and try again.

@asishrs Just to close my issue out. I had to delete the Lambda from the last setup, delete the new SmartApp, and then start over. It still took a few tries, but eventually I was able to enable 2FA and get through the rest of the new setup. It appears to be working very well. Thank you for coding this new version. I hope you can eventually figure out a way to status the devices within seconds. I think that's all that's left to make this integration flawless!

**Comment by elnorte13524** [comment]
Im probably doing something dumb, but im working on creating a Stack on AWS, where im supposed to upload the file.  I see the github link to the code, but i cant figure out how to download the .yaml file from there.  can someone point me in the right direction?

**Comment by asishrs** [comment]
You can either clone the repository using `git` commmad or open https://github.com/asishrs/smartthings-ringalarmv2/blob/master/aws/ringalarm-gateway.yaml in your browser click on the **Raw** option. This will open the file content in a new tab, from that you can copy entire file content and save that as `ring alarm.yaml` file

**Comment by elnorte13524** [comment]
thanks!  i figured out how to download everything in the repo and got the file from there.  i tried to save the raw as a txt (like ive dont many times for batch files) but notepad just kept adding .txt to the end.  i got the file uploaded and im on my way, but something else was requesting 2FA OTP so my ring account is locked out.  Once they get me unlocked, i should be all set, i just need to finish the app config in the ST classic app.  Thanks for an awesome app and device handlers!
