### ISSUE TITLE
ActionTiles

### ISSUE THREAD

**Issue by GizmoGoody** [asishrs/smartthings-ringalarmv2#2]
Thank you. Would each sensor need to be added as child devices first to be able to see them in ActionTiles IAW these two posts?

https://support.actiontiles.com/knowledge-bases/8/articles/363-some-devices-are-missing-from-the-authorize-things-add-location-screen

https://support.actiontiles.com/communities/12/topics/1091-switch-tile-is-not-updating-when-activated-from-another-devicealexa

**Comment by asishrs** [comment]
Yes that's totally possible. based on my initial reading this requires a lot of work. I can take a look into this later.

**Comment by GizmoGoody** [comment]
It seems @javier-jm  is onto a solution (https://github.com/javier-jm/smartthings) although I'm having a hard time getting the Child Devices back after a reinstall (https://github.com/asishrs/smartthings/issues/6).

**Comment by haideramn** [comment]
Was anyone able to do what @Javier-JM has outlined and get the Ring Sensors to show up as individual sensors to run actions/webcore against?

**Comment by GizmoGoody** [comment]
> Was anyone able to do what @javier-jm has outlined and get the Ring Sensors to show up as individual sensors to run actions/webcore against?

@haideramn It appears @asishrs plans to get this working in a future enhancement. See issue https://github.com/asishrs/smartthings-ringalarmv2/issues/12.

**Comment by asishrs** [comment]
@haideramn I know people using @javier-jm solution with the webcore. You can try. Eventually we will merge this to master.

**Comment by asishrs** [comment]
Merged @javier-jm 's work in the latest version
