### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by ghost** [asishrs/smartthings-ringalarmv2#20]
Just noticed Ring hasn't been updating for 8 hrs. Looking at the Live Logging in SmartThings, error:  

Ring Alarm Status check Error: groovyx.net.http.HttpResponseException: Bad Gateway.

I have been running this flawlessly for almost a year, this is the first issue. Is this finally the end of this integration?

**Comment by asishrs** [comment]
I am seeing same. I need to check ring APIs. This is my priority for weekend.

**Comment by asishrs** [comment]
@bconrad0321 I fixed this issue, testing looks good on my side. Deploy v1.2 from https://github.com/asishrs/smartthings-ringalarmv2/releases/tag/1.2 

You can update the current lambda function using the new deployment.zip file. Instructions https://github.com/asishrs/smartthings-ringalarmv2/releases/tag/1.2

**Comment by SarcasmRules** [comment]
It solved my issue too! I posted a bug in version V1 (while using V2), sorry should have looked here. Thanks!

**Comment by Its2loud1** [comment]
You can update the current lambda function using the new deployment.zip file. Instructions https://github.com/asishrs/smartthings-ringalarmv2/releases/tag/1.2

where are the instructions in that link?

**Comment by SarcasmRules** [comment]
> where are the instructions in that link?

Simply download the zip file and go back to the original instruction where you upload the deployment file in your lambda function

**Comment by Its2loud1** [comment]
Just figured that out.  Thanks.  Is anyone seeing the ST alarm status change when arming Ring from the Ring app?  I can change status of Ring from ST app but not the other way around. I have the polling set to 1 minute but there is no update from the ST side of things.  It's also not seeing any of my door sensors or motion detectors.  I have updated them in device handler code but no luck.

**Comment by SarcasmRules** [comment]
No, it works from both apps, bi-directional, on my end. I saw your posts on ST that you're having issues for the last 5 months, perhaps start from scratch?

**Comment by Its2loud1** [comment]
Thanks.  Yeah. I've done that three times I think by now.  Meticulously followed directions.  Even tried using both east cost AWS Lambdas with no luck.

**Comment by SarcasmRules** [comment]
FWIW, I'm on west AWS
[https://us-west-1.console.aws.amazon.com/lambda/home?region=us-west-1#/functions](https://us-west-1.console.aws.amazon.com/lambda/home?region=us-west-1#/functions)

**Comment by Its2loud1** [comment]
ok thanks.  I'll try that one.  The trouble I'm having now is the instructions are outdated now.  AWS has changed some of the options on their Lambda creation page and some of the areas Asishrs describes in the instructions don't exist anymore.

**Comment by SarcasmRules** [comment]
Yes, I ran into that too a couple of months ago; however, dig in there as the options are still there just hidden and revealed by selection.
- Click on Create Function -> Enter your function name and select Go 1.x as runtime and click the orange create function (save) button at the bottom (without selecting anything else).
- This takes you to a new screen where you need to click on "Add Trigger" where yo add the API Gateway as per instructions (make sure you select REST) and the block below you upload the "development.zip" file, and edit other fields as per instructions.
-From here you should be able to follow the rest

**Comment by haideramn** [comment]
I uploaded the new deployment file under the existing function, and saved it, but no luck, am I missing anything? ST still cannot control Ring.

**Comment by KennethScott** [comment]
> 
> 
> I uploaded the new deployment file under the existing function, and saved it, but no luck, am I missing anything? ST still cannot control Ring.

Same here.  There's obviously a little more to it than that.  I'm sure it's obvious to those more familiar with AWS but a little guidance would be appreciated.

**Comment by SarcasmRules** [comment]
> > I uploaded the new deployment file under the existing function, and saved it, but no luck, am I missing anything? ST still cannot control Ring.
> 
> Same here. There's obviously a little more to it than that. I'm sure it's obvious to those more familiar with AWS but a little guidance would be appreciated.

Try to re-enter your login and pass in the app and save.

**Comment by RosTeHeA** [comment]
Thank you! I wondered what had happened...

And @assishrs THANK YOU for this integration. It has been wonderful.

**Comment by dmoses1969** [comment]
> > > I uploaded the new deployment file under the existing function, and saved it, but no luck, am I missing anything? ST still cannot control Ring.
> > 
> > 
> > Same here. There's obviously a little more to it than that. I'm sure it's obvious to those more familiar with AWS but a little guidance would be appreciated.
> 
> Try to re-enter your login and pass in the app and save.

Where do you enter your login and pass in the app? Ring Alarm State App?

**Comment by SarcasmRules** [comment]
(iphone) open ST App, go to "My Home" - "Things" and click on your "RING Alarm". In the upper right corner is a gear wheel which you click on. There you enter your username (email) and password to which you log in to ring website/account. Don't forget to click on "save"  (upper right corner). I don't have an android but i'm sure it is relatively the same.

**Comment by dmoses1969** [comment]
> (iphone) open ST App, go to "My Home" - "Things" and click on your "RING Alarm". In the upper right corner is a gear wheel which you click on. There you enter your username (email) and password to which you log in to ring website/account. Don't forget to click on "save" (upper right corner). I don't have an android but i'm sure it is relatively the same.

Thanks. That worked
