### ISSUE TITLE
WebCore Commands

### ISSUE THREAD

**Issue by jaas666** [asishrs/smartthings-ringalarmv2#22]
Greetings thanks for your hard work.

All I need is to be able to auromatically arm my alarm everyday at a specified time.

I'm trying to do this with WebCore but when trying to build my piston I notice that the away and off commands are present, but not the HOME command.

Do you know why is this?

**Comment by jaas666** [comment]
Managed to get it to work. For some reason the HOME command does not show on Webcore.. I copied the HOME command definition and created HOMETEST command in the device handler. The HOMETEST command I created shows up on webcore but the original HOME does not.

Not sure why but at least I found a workaround and my alarm now auto arms as expected.

**Comment by asishrs** [comment]
> Managed to get it to work. For some reason the HOME command does not show on Webcore.. I copied the HOME command definition and created HOMETEST command in the device handler. The HOMETEST command I created shows up on webcore but the original HOME does not.
> 
> Not sure why but at least I found a workaround and my alarm now auto arms as expected.

Thanks for the update. I will check and make changes in the code if needed.

**Comment by asishrs** [comment]
@jaas666 Added methods `triggerhome()`, `triggeraway()`, `triggeroff()` in the new version of the Device Handler in https://github.com/asishrs/smartthings Please test that and let me know in case of any issues.
