### ISSUE TITLE
Stopped working about 10 days back

### ISSUE THREAD

**Issue by schpeen** [asishrs/smartthings-ringalarmv2#23]
I just noticed today that my Ring Alarm in ST app hasn't updated since January 10th. It was all working perfectly so not sure what changed. Anything new I need to do?? Thanks for help.

**Comment by asishrs** [comment]
Did you check this https://github.com/asishrs/smartthings-ringalarmv2/issues/20#issuecomment-573288928

**Comment by schpeen** [comment]
Thank you that worked. Sorry didn't see this fix. Appreciate the help
