### ISSUE TITLE
Mode Labels and Order

### ISSUE THREAD

**Issue by GizmoGoody** [asishrs/smartthings-ringalarmv2#3]
I'd like to change the name and order of the Ring Alarm modes to match the Ring iOS App (Disarmed|Home|Away). @asishrs would you be interested in changing that or could you advise how I would do that for my version?

**Comment by asishrs** [comment]
Thanks for the feedback! I will update this soon.

**Comment by GizmoGoody** [comment]
Did you decide it wasn't worth moving the icons around and changing the labels to match the Ring app?

**Comment by asishrs** [comment]
I didn't get a chance to work on this yet. Will include in the next update.

**Comment by GizmoGoody** [comment]
Great, thank you!

**Comment by GizmoGoody** [comment]
@asishrs I think the new version fixed the order, but can you change the OFF label to DISARMED like in the Ring App?

**Comment by asishrs** [comment]
Fixed in https://github.com/asishrs/smartthings/blob/master/RELEASE.md#release-v-330

**Comment by GizmoGoody** [comment]
@asishrs Looks great. Thank you!
