### ISSUE TITLE
Motion and Door Contact

### ISSUE THREAD

**Issue by seanpbrandon** [asishrs/smartthings-ringalarmv2#32]
Thank you so much for this.  I have been using for quite some time now and it works great!  With the new version, what is the point of motion and door contact if it is polling every 1 minute?

**Comment by asishrs** [comment]
At present, the lowest level of polling support in ST is one minute.  I am investigating a way to do this https://github.com/asishrs/smartthings/issues/18

**Comment by asishrs** [comment]
Closing this as I am tracking this in https://github.com/asishrs/smartthings/issues/18
