### ISSUE TITLE
2FA authentication not working

### ISSUE THREAD

**Issue by Its2loud1** [asishrs/smartthings-ringalarmv2#33]
![02B0E94C-5BB2-44EA-859F-21FD2FB1FB16](https://user-images.githubusercontent.com/49612825/74898212-14382600-534e-11ea-992e-d79009adc056.jpeg)
Asishrs,
I think Ring broke the 2FA With their latest app release. My Ring integration isn’t working anymore. Can you check?  I haven’t changed anything on any of my setup and as of yesterday it all stopped working. Thanks. 

Upon further investigation I think Ring is blocking the AWS call to Ring. I received an email from Ring telling me a new device or web browser was attempting to login to my account.  They wanted me to enter in the code to verify it was me. However, there is no way for me to enter this code since I don’t have a way of doing that. This was different from the 2FA authentication from the app. 

![9C986836-6100-4CF8-9C84-797FB3A2BEA4](https://user-images.githubusercontent.com/49612825/74898840-f10e7600-534f-11ea-880c-28cf25cde358.jpeg)

**Comment by asishrs** [comment]
Working as expected. Not sure whether they are rolling out changes in batch.

It looks like your ST apps token got overridden. You can reinstall the app to fix this.

**Comment by Its2loud1** [comment]
Reinstall the smart app?  Yep.  That fixed it. Strange. I went to turn on 2FA in the  Smart App and everything went broke. Deleted and reinstalled and everything happy again. Not sure what went wrong.  I’ll let you know if I get another one of those emails again and if it breaks in 24 hours.

**Comment by burn56** [comment]
Holy shit. 
I’m over here after changing my password thinking I broke it.
I was changing my password because I too got the email.
After reinstalling and recreating the API, I’m happy to find that uninstalling and reinstalling the app resolved it!

**Comment by richleyh** [comment]
Yes, I too received the email and reset my password. I am again trying to install this integration, this time with 2FA (as I understand it will soon be required by Ring anyway), and after entering the code I receive, I click on "Ring Account Status" to (hopefully) see my zid, and instead this triggers another code to be sent to me. Here are the errors triggered when I tap on Ring Account Status:

<img width="1137" alt="Screen Shot 2020-02-22 at 8 06 12 AM" src="https://user-images.githubusercontent.com/49592858/75093804-aad13680-554a-11ea-8843-42097d887ab2.png">

I have also uninstalled and re-installed the smart app as mentioned above, but continue to have this issue...thanks in advance for any help you can offer!

**Comment by Its2loud1** [comment]
It worked for me when I removed the smart app and reinstalled it and entered everything fresh from the start. When you set up thec Ring account info, make sure you turn on 2FA before entering your username and password. Do NOT turn on the button for “Do you want to use a s existing Ring Account refresh key” this did not work for me. Just follow the prompts for two factor authorization and enter the code Ring sends you. Also, make sure you actually enabled 2FA in your Ring account. 

Make sure to click all of the “Done” and “Save”. Do not just back out of the smart app.  Once you’ve entered everything click on Ring Account Status and you should see your ZID and Location ID. 

Hope this helps.

**Comment by richleyh** [comment]
Thanks so much for trying to help me. So, I actually deleted my AWS account and started over completely, from start to finish, in case there was something that perhaps I didn't remove from the previous install, etc. However, I continue to have this persistent problem. Tpping "Ring Account Status" simply causes another code to be sent to me, and produces these log entries:

<img width="1207" alt="Screen Shot 2020-02-22 at 10 50 17 AM" src="https://user-images.githubusercontent.com/49592858/75096089-85035c00-5561-11ea-85e5-affc3b443572.png">

I know my Ring login info is correct. If it were not, I would not receive a code. I have followed the install instructions to the letter. In reviewing the install process, here are points I see as potential spots for error on my part:

- I should be uploading the entire deployment.zip file to the bucket, correct? I should not be un-zipping the file and uploading it's contents?

    Everything else seems quite clear to me. Yet it doesn't work. I am baffled. Any help would be appreciated!

Rich

**Comment by Its2loud1** [comment]
“I should be uploading the entire deployment.zip file to the bucket, correct? I should not be un-zipping the file and uploading it's contents?”

I did not unzip the contents. I just uploaded the Zip file as is.

**Comment by asishrs** [comment]
Yes, upload the zip file. No need to unzip.

**Comment by schpeen** [comment]
So I am currently getting non stop emails from ring with codes and I am guessing its from this. I finally turned on 2fa today because I guess Ring is forcing everyone to use it so I figured turn it on. So what should I change to fix this ??

**Comment by schpeen** [comment]
well i started over from scratch, and now I cannot get the 2FA to work. I put in my correct rng email and password , then enter the code I get but then when I hit check ring account status I get nothing or another code.

**Comment by schpeen** [comment]
Do I need to enable oauth in the smart app ?

**Comment by Its2loud1** [comment]
There’s no reason to start from scratch. You only risk the possibility of messing up the AWS setup. What worked for me was removing the Smart App and then Reinstalling from the Classic App. The. Re-enter all of the setup info and turn on the slider for Two-Factor Authorization. Enter your Ring account info and all the rest will fall into place. I had problems trying to change over to 2FA if I had the account integration already setup in the ST app.  Also be sure to hit “Done” and “Save” in the Smart app. Do not just back out of the app.

**Comment by schpeen** [comment]
I tired that at first and didn’t work so I went ahead and just did it all over. Everything is fine except now it won’t let me review the account status. I think I tried so many times now it’s not sending me codes anymore. It’s something to do with the 2fa. Is the latest app the one in github repository?

**Comment by Its2loud1** [comment]
This one

https://github.com/asishrs/smartthings

If you didn’t authorize the app soon enough it’s possible Ring blocked it from trying again. You’ll need to remove and install again. Just the smart app.

**Comment by schpeen** [comment]
Yep they froze my account for 24 hours....thats a bit drastic and exactly why I dont like using 2FA not sure why they are forcing people. I use very complex passwords so no need for it.

**Comment by alijaf123** [comment]
I am getting the messages that someone is trying to access your ring
account.

**Comment by richleyh** [comment]
Yes, I received these as well. Wish I had a solution. Had to delete the smart app and call Ring to regain access.

**Comment by asishrs** [comment]
If you (or Ring) enable 2FA on your account and the ST app is not configured with 2FA, each request to poll from the ring will result in a 2FA request.

Ring will disable login from new devices up to 24 hours if you are unsuccessful in authenticating to an account with 2FA protected for a longer period of time.

If your account is disabled, either wait for 24 hours or call Ring support to enable it.

If you are keep getting 2FA code on a registered mobile either uninstall the ST app or “Pause the integration” using the option under “AWS API I lntegration” section.

**Comment by asishrs** [comment]
For my understanding, are you seeing these issues after Ring enabled 2FA on your account?

I am running new version with 2FA enabled for more than a month now.

**Comment by Its2loud1** [comment]
Asish,
I think the issues started happening when Ring started rolling out the forced 2FA. It wasn’t a problem when you voluntarily did the 2FA. Like in my first post, the email went out asking for login verification and code entry into the browser. If you didn’t do that, they blocked that device from trying to login again, thus my expired tokens which you helped me reset. Once 2FA was setup in Ring, the only way I could get the integration to work was to remove the smart app and reinstall and setup again with 2FA on. Pausing the integration while setting up the 2FA might help but I didn’t try that. Hopefully there is enough description here to help people with the 2FA. Once I set it back up I have not had any problems.

**Comment by asishrs** [comment]
@Its2loud1 thanks for the details.

**Comment by schpeen** [comment]
its so strange I cannot for the life of me get this to work. Even deleted app and reinstalled it. I even tried pausing APS and trying to finish the 2fa but when I enter the code and touch get ring account status it just sends me another code and never shows me anything. So upset they are forcing people to use 2fa all my stuff was working perfectly and now I am stuck...bummer.

**Comment by schpeen** [comment]
even if I turn off 2fa i cant get it to work now. Gotta be something else then.

**Comment by Its2loud1** [comment]
Did you choose your alarm under these settings?

![38442228-24E0-4869-B0A5-BBBA26E68D5A](https://user-images.githubusercontent.com/49612825/75370554-1f251600-587a-11ea-8948-53319e67794c.png)

**Comment by schpeen** [comment]
Yes i did. I added the Ring alarm as it stated as a device, and then in the Ring Alarm app I selected that alarm for it to use.

**Comment by Its2loud1** [comment]
> its so strange I cannot for the life of me get this to work. Even deleted app and reinstalled it. I even tried pausing APS and trying to finish the 2fa but when I enter the code and touch get ring account status it just sends me another code and never shows me anything. So upset they are forcing people to use 2fa all my stuff was working perfectly and now I am stuck...bummer.

Try these steps...

1. Disable 2FA in Ring. I believe you can still do this. 

2. Remove Ashishrs smart app from the classic app

3. Re-add the smart app from the classic app in Automation-> SmartApp->add a smart app.  Do Not do anything with the smart app yet. 

4. In the Ring app enable 2FA

5. Go back to the ST app and setup it up accordingly with 2FA enabled. 

6. Enter the text code Ring sends you

7. Click Done and Save. 

8. If you still do not see your Ring status in the smart app then there is possibly something wrong with the AWS setup. 

I have not had any issues with the integration since Ring started changing things.

**Comment by schpeen** [comment]
Okay..Thanks for info and I will try it later. Do I click on RIng status ?? Or does it just populate once I put code in? just curious because that seems the to be the problem part for me. If your tip doesn't work i will just start over again I guess and try again. Thanks again.

**Comment by Its2loud1** [comment]
It will auto populate once it logs into Ring. You can click on to check the status. 

One more thing to check is you AWS API setup. Make sure you entered all of that correctly.

**Comment by schpeen** [comment]
Phew!! Finally got it. Thanks for help. Not sure what was so different this time but at first it didnt work then i backed out of the Ring account part went back into it and tried again and boom it finally took and gave me location ID. Thanks for the info and help appreciate it.

**Comment by Its2loud1** [comment]
Glad you got it working. No problem

**Comment by seanpbrandon** [comment]
Thank you @Its2loud1 .  Saved me after 4 days of yelling and 24 hour lockouts!
