### ISSUE TITLE
Changing alarm mode from SmartThings

### ISSUE THREAD

**Issue by badamonis** [asishrs/smartthings-ringalarmv2#34]
Apologize if I misunderstand how this should work. I have everything set up and devices and status are successfully polled and reflected within ST. However, if I try to change the model from ST, it does not reflect on the Ring side. After the next polling interval, ST will update to the current mode. So while it is able poll data, it isn't able to push changes. Is this what is intended? I can see the API call go out, and it says it is successful, but I see not changes reflected on the Ring side.

IDE log:

 10:27:18 PM: debug Ring Alarm is Armed AWAY
 10:27:17 PM: debug send() -> sending push message
 10:27:17 PM: info setalarmaway() -> Ring Alarm is Armed AWAY
 10:27:17 PM: trace ringApiCall() -> Ring Alarm AWAY response data: [message:Success]
 10:27:16 PM: info ringApiCall() -> Calling AWS API for Ring Alarm with route `away`. API Call ready - true
 10:27:16 PM: debug setAlarmModeBasedOnDeviceTrigger() -> Current alarm state is: home
 10:27:16 PM: debug setAlarmModeBasedOnDeviceTrigger() -> Setting Ring Alarm mode Ring Alarm to away
 10:27:16 PM: info alarmStateHandler() -> away

Lambda log:

03:27:16 - START RequestId: 14cfbb82-1f27-446e-ba52-4fdb8b5f7778 Version: $LATEST
03:27:16 - Version 2.3
03:27:16 - Using Refresh Token to Authenticate Ring API
03:27:17 - Timeout after 1 seconds
03:27:17 - read: read tcp 169.254.76.1:51464->34.229.13.233:443: use of closed network connection
03:27:17 - END RequestId: 14cfbb82-1f27-446e-ba52-4fdb8b5f7778
03:27:17 - REPORT RequestId: 14cfbb82-1f27-446e-ba52-4fdb8b5f7778 Duration: 1173.93 ms Billed Duration: 1200 ms Memory Size: 512 MB Max Memory Used: 53 MB

**Comment by asishrs** [comment]
Yes, you can change the status using ST Device Handler. The api call happens immediately, and the ring alarm mode should switch to the corresponding status. You can see the same on your Ring App as well.

**Comment by badamonis** [comment]
Thanks. Any ideas on troubleshooting why DH changes aren’t reflecting on Ring side? Like I mentioned, I can change on Ring side and within the polling cycle, it will update ST but if I make changes in ST, it won’t update Ring at all.

**Comment by adessmith** [comment]
Similar issue here.
I recently tried to update to the latest version and now I can't get it working. The child devices show up and report status correctly. The alarms status seems to be reported correctly, but I can not change the alarm mode from within smartthings... For instance, if I set the alarm to "home", It acts like it sends the command but the alarm mode never changes. Then, after the next poll the smartthings app updates and says the alarm was turned off.
Changing the mode manually on the alarm or through the ring app reports correctly in the smartthings app the next time it polls.

**Comment by asishrs** [comment]
I will check this. Give me few days.

**Comment by mpclimber** [comment]
I'm having the same issue as above.  Had no problems with V1 or with V2 until 2FA.  Finally got 2FA working in v3 (location id and ZID correctly show in status, all devices correctly poll in ST app, no error messages or constant tokens being generated).  

However,  ST app will not change alarm states on the actual alarm (neither manually nor automated).

**Comment by adessmith** [comment]
Yeah, I give up... I've spent an hour or two every night for the last two weeks trying to get mine working again. Worked great until I updated to V3... I've removed everything and started over completely a few times, I've poked around all the settings, tried with and without 2FA, etc... It seems to be "talking" because I can see the status of everything from ST, but I just can't change the alarm mode. It acts like it changed in ST (but never on the alarm itself) but then the next time it polls it goes back.
I'm very confused... is ANYONE running V3 with this working? and don't you have to move to V3 for 2FA? Is it possible to go back to V2?

**Comment by mpclimber** [comment]
> Yeah, I give up... I've spent an hour or two every night for the last two weeks trying to get mine working again. Worked great until I updated to V3... I've removed everything and started over completely a few times, I've poked around all the settings, tried with and without 2FA, etc... It seems to be "talking" because I can see the status of everything from ST, but I just can't change the alarm mode. It acts like it changed in ST (but never on the alarm itself) but then the next time it polls it goes back.
> I'm very confused... is ANYONE running V3 with this working? and don't you have to move to V3 for 2FA? Is it possible to go back to V2?

Same here.  I'm about to give up as well after one more from scratch delete and install, however, I'd prefer to try to reinstall V2 but can't seem to find the code anywhere.

**Comment by asishrs** [comment]
Do you have more than one ring alarm base station or multiple location on your account?

**Comment by mpclimber** [comment]
Only over ring alarm but I've always had 2 locations.  It was a strange bug when I first installed my hub and it gives an error message whenever I try and delete the second location.  
On Monday, March 23, 2020 asish <reply@reply.github.com> wrote:



Do you have more than one ring alarm base station or multiple location on your account?

**Comment by asishrs** [comment]
Can you remove second location from ring and complete the installation? Once you finish the installation, you can add second location back to the ring alarm.

The ST app doesn’t support multiple locations.

**Comment by mpclimber** [comment]
I dont want multiple locations but have never been able to remove the second.  I get an error message even though there are no devices on that location.
On Monday, March 23, 2020 asish <reply@reply.github.com> wrote:



Can you remove second location from ring and complete the installation? Once you finish the installation, you can add second location back to the ring alarm.

The ST app doesn’t support multiple locations.

**Comment by mpclimber** [comment]
I managed to delete the second location.  Thanks for the motivation to figure out how to do that.  However, I deleted the app and device and started over again and no change.  The app still polls all devices correctly, but won't change modes on the alarm itself.  
On Monday, March 23, 2020 asish <reply@reply.github.com> wrote:



Can you remove second location from ring and complete the installation? Once you finish the installation, you can add second location back to the ring alarm.

The ST app doesn’t support multiple locations.

**Comment by asishrs** [comment]
Can you check the device logs in the ST IDE and check for errors?

**Comment by mpclimber** [comment]
Here's the output of the log:662b4233-c0fb-42d0-8e41-0b7174c02d51 6:18:41 PM: debug Ring Alarm is DISARMED662b4233-c0fb-42d0-8e41-0b7174c02d51 6:18:41 PM: debug send() -> sending push message662b4233-c0fb-42d0-8e41-0b7174c02d51 6:18:41 PM: info setalarmoff() -> Ring Alarm is DISARMED662b4233-c0fb-42d0-8e41-0b7174c02d51 6:18:41 PM: trace ringApiCall() -> Ring Alarm OFF response data: [message:Success]662b4233-c0fb-42d0-8e41-0b7174c02d51 6:18:40 PM: info ringApiCall() -> Calling AWS API for Ring Alarm with route `off`. API Call ready - true662b4233-c0fb-42d0-8e41-0b7174c02d51 6:18:40 PM: debug setAlarmModeBasedOnDeviceTrigger() -> Current alarm state is: home662b4233-c0fb-42d0-8e41-0b7174c02d51 6:18:40 PM: debug setAlarmModeBasedOnDeviceTrigger() -> Setting Ring Alarm mode Ring Alarm Integration to off662b4233-c0fb-42d0-8e41-0b7174c02d51 6:18:40 PM: info alarmStateHandler() -> off662b4233-c0fb-42d0-8e41-0b7174c02d51 6:18:40 PM: trace ringApiCall() -> Ring Alarm STATUS response data: [deviceStatus:[[faulted:false, id:e25e3117-9e22-4f25-aefe-bffe7b7dec11, mode:, name:ZigBee onboard adapter, type:adapter.zigbee], [faulted:false, id:7533c5aa-d7be-4bd2-b43f-97756c17a7a3, mode:, name:Code Vault, type:access-code.vault], [faulted:false, id:9f391f96-abe2-4747-8d4d-1ba010ee2f7b, mode:none, name:Ring Alarm, type:security-panel], [faulted:false, id:14ec1875-36b8-4d0e-8e63-e694744872cb, mode:, name:Security Access Code, type:access-code], [faulted:false, id:b5573a94-3d9a-474c-9ba2-10e8f919917c, mode:, name:Base Station, type:hub.redsky], [faulted:false, id:b4b1c8b4-7068-4787-9236-15f49b4cb695, mode:, name:Z-Wave Adapter, type:adapter.zwave], [faulted:false, id:fbf27ad3-e218-4bc0-9efc-d4e177d60846, mode:, name:Front Door Ring Contact Sensor , type:sensor.contact], [faulted:true, id:002db3df-16e6-42f3-88b0-938f85f8a94d, mode:, name:Family Room Ring Motion Sensor, type:sensor.motion], [faulted:false, id:f618dba5-4e50-429b-a689-0797018add70, mode:, name:Ring Keypad, type:security-keypad], [faulted:false, id:86838515-e91b-4366-bff0-7bf3c52cf5ca, mode:, name:Ring Z-Wave Extender 53980, type:range-extender.zwave], [faulted:false, id:25a51f73-0e11-46be-8304-5d349771ef2a, mode:, name:2nd Floor Ring Motion Sensor, type:sensor.motion], [faulted:false, id:a6d03255-b89d-428a-bf0b-4c85a07330b5, mode:, name:Mud Rm Door Ring Contact, type:sensor.contact], [faulted:false, id:5eac296b-adb8-48cb-a21c-2460b494b602, mode:, name:Deck door Ring Contact Sensor 41485, type:sensor.contact], [faulted:false, id:ca2e63b6-17ba-4f2f-b9e3-8ae27bcc938c, mode:, name:First Alert Smoke Alarm 1, type:alarm.smoke], [faulted:false, id:f79b2d87-50f4-4f27-8dba-02d121395824, mode:, name:First Alert CO Alarm 1, type:alarm.co], [faulted:false, id:a7e1c8e1-6ed5-4bbf-aeca-9bba580d0a86, mode:, name:GR Sliding Ring Contact Sensor 35837, type:sensor.contact], [faulted:false, id:a1f78a77-72ec-49da-9a69-481b4a481d26, mode:, name:Hallway Smoke/CO Listener, type:listener.smoke-co], [faulted:false, id:a1a9b...[TRUNCATED]662b4233-c0fb-42d0-8e41-0b7174c02d51 6:18:37 PM: info ringApiCall() -> Calling AWS API for Ring Alarm with route `status`. API Call ready - true662b4233-c0fb-42d0-8e41-0b7174c02d51 6:18:37 PM: debug updateChildDeviceStatus() -> Updating Child Device Status662b4233-c0fb-42d0-8e41-0b7174c02d51 6:18:40 PM: info alarmStateHandler() -> off662b4233-c0fb-42d0-8e41-0b7174c02d51 6:18:32 PM: debug Ring Alarm is Armed HOME662b4233-c0fb-42d0-8e41-0b7174c02d51 6:18:32 PM: debug send() -> sending push message662b4233-c0fb-42d0-8e41-0b7174c02d51 6:18:32 PM: info setalarmhome() -> Ring Alarm is Armed HOME662b4233-c0fb-42d0-8e41-0b7174c02d51 6:18:32 PM: trace ringApiCall() -> Ring Alarm HOME response data: [message:Success]662b4233-c0fb-42d0-8e41-0b7174c02d51 6:18:31 PM: info ringApiCall() -> Calling AWS API for Ring Alarm with route `home`. API Call ready - true662b4233-c0fb-42d0-8e41-0b7174c02d51 6:18:31 PM: debug setAlarmModeBasedOnDeviceTrigger() -> Current alarm state is: off662b4233-c0fb-42d0-8e41-0b7174c02d51 6:18:31 PM: debug setAlarmModeBasedOnDeviceTrigger() -> Setting Ring Alarm mode Ring Alarm Integration to home662b4233-c0fb-42d0-8e41-0b7174c02d51 6:18:31 PM: info alarmStateHandler() -> home

-----Original Message-----

**Comment by adessmith** [comment]
I have also had this issue for the past month and I've only ever had one alarm base station and one location on my account.

**Comment by asishrs** [comment]
Released a [new version](https://github.com/asishrs/smartthings/blob/master/RELEASE.md#release-v-330) which displays the Location details under **Ring Account >  Ring Account Status > Ring Location**

Can you check whether you are seeing right location under that? Also, please make sure that you are using 2FA with your ring account.

**Comment by mpclimber** [comment]
Completely rebuilt the lambda from scratch and updated the device handler and app, deleted and reinstalled the device and then reconfigured the app.  
Yes, the correct location is showing up and 2FA is working correctly and I'm getting correct logging of alarm state status.  I just can't cause the app to change modes.  

In the ring app itself, I'm not seeing an entry in authorized devices for this.  I'm just seeing my phone, my wife's phone and the windows desktop application.  No entry for what should show as a separate device, because I have competed the 2FA authorization.  Very strange.

**Comment by asishrs** [comment]
>In the ring app itself, I'm not seeing an entry in authorized devices for this. I'm just seeing my phone, my wife's phone and the windows desktop application. No entry for what should show as a separate device, because I have competed the 2FA authorization. Very strange.

That's because the app connects as your phone - `ring_official_ios`. Check this line https://github.com/asishrs/smartthings-ringalarmv2/blob/master/main.go#L32

**Comment by asishrs** [comment]
@mpclimber can you check the logs corresponding to the mode changes and share that with me?

**Comment by mpclimber** [comment]
![log](https://user-images.githubusercontent.com/29009389/78622375-f74ea800-7852-11ea-9517-b458f81beb7a.JPG)

**Comment by asishrs** [comment]
This is from Device Handler, can you get the Smart App logs?

**Comment by mpclimber** [comment]
![log2](https://user-images.githubusercontent.com/29009389/78623080-d5562500-7854-11ea-9857-5d491721a69c.JPG)

**Comment by mpclimber** [comment]
![log3](https://user-images.githubusercontent.com/29009389/78623184-0fbfc200-7855-11ea-8026-c3a1f848892f.JPG)

**Comment by asishrs** [comment]
This looks clean as well. Can you share the AWS lambda logs from Cloud Watch ?

**Comment by mpclimber** [comment]
![Lambda log](https://user-images.githubusercontent.com/29009389/78624837-932ee280-7858-11ea-81a3-8556852c0238.JPG)

**Comment by mpclimber** [comment]
I keyed to the same time period.

**Comment by asishrs** [comment]
this looks clean as well 🤦‍♂

**Comment by asishrs** [comment]
I created a debug build for you - https://github.com/asishrs/smartthings-ringalarmv2/actions/runs/72360621 Can you deploy the deployment.zip from that in AWS lambda and get me the logs.

**Comment by asishrs** [comment]
Check this comment https://github.com/asishrs/smartthings-ringalarmv2/issues/43#issuecomment-612692943

**Comment by adessmith** [comment]
I updated to the latest version, now it doesn't seem to sync the current status anymore either... so it's basically not working at all. I get no events in my history in smartthings and when I try to change modes from ST it just hangs at pending.
I wonder how many people having this issue have smart locks paired with their ring system?

**Comment by adessmith** [comment]
I just deleted the smartapp and reinstalled it and its back to the "regular broken" state it has been in since February. It is now properly polling the alarm status, but changes to the alarm status from the ST app do not "take". If this is still working correctly for some people, but not others, I wonder how many people use smart locks with their ring alarm system, and if ring has done something to stop 3rd party changes for systems with locks...

**Comment by asishrs** [comment]
@adessmith maybe these are related. Can you share the logs? https://github.com/asishrs/smartthings-ringalarmv2/issues/43#issuecomment-612692943

**Comment by mpclimber** [comment]
I'm planning to update the code tomorrow.  

I DO have a schlage connect lever door lock that's integrated/paired with the ring alarm. 

I'm also in 2 of ring's beta programs:
1. rapid ring app (but I still have and use the regular ring app as well).
2. upcoming 2nd gen ring alarm keypad and sensors. 

Not sure if that has a bearing on this, but figured I'd flag anything unique about my setup.
On Friday, April 17, 2020 asish <reply@reply.github.com> wrote:



@adessmith maybe these are related. Can you share the logs? #43 (comment)

**Comment by mpclimber** [comment]
Everything updated and still not working.  Any leads?

**Comment by kevinpride** [comment]
I am having the same issue. Starting from "Arm Away" mode, if I "disarm" in ST, it will show "Pending Disarm". Then a few seconds later, it will go back to "Arm Away" mode. The mode in the Ring app doesn't change at all. It looks for some reason the SHM mode is not pushing mode change to Ring Alarm. Any help on this would be appreciated.

**Comment by asishrs** [comment]
can you share the list of devices added to your Ring account?

**Comment by kevinpride** [comment]
I have several Ring devices. The list is below. I have the Ring Alarm Base Station and Keypad. I guess they show up just once as "Ring Alarm". Thank you.

Ring Doorbell Pro
Ring Spotlight Cam Battery
Ring Alarm
Ring Contact sensor x 6
Ring Motion Sensor

**Comment by asishrs** [comment]
Several people with a Door Lock added to the account said that the setup is not working for them. Thats why I asked the list of devices. Looks like you don't have a lock. Do you have any non-ring branded device added to the account?

**Comment by mpclimber** [comment]
I also have a schlage door lock.  Has removing the door lock solved the problem for anyone?

On Sunday, May 24, 2020 asish <reply@reply.github.com> wrote:



can you share the list of devices added to your Ring account?

**Comment by asishrs** [comment]
I am not aware of that. If it’s easy, you may want to try that.

**Comment by badamonis** [comment]
I too had a Schlage lock connected to Ring. I can confirm that once I removed it (I moved over to RBoy) and re-set up the Ring Alarm manager integration, it works both ways (instantaneous when changes are initiated from ST and within polling cycle when changes are initiated from Ring app side).

**Comment by asishrs** [comment]
Thanks for sharing this.

**Comment by mpclimber** [comment]
Confirmed, removal of schlage lock solved the problem for me as well.
On Sunday, June 7, 2020 asish <reply@reply.github.com> wrote:


I am not aware of that. If it’s easy, you may want to try that.

**Comment by kevinpride** [comment]
Removing the Schlage lock fixed problem for me as well.
