### ISSUE TITLE
Ring Alarm not working

### ISSUE THREAD

**Issue by DjAnu** [asishrs/smartthings-ringalarmv2#36]
Wondering if any one else is experiencing this problem as well ? My Ring Alarm app has started giving this error since yesterday:

Ring Alarm Status check Error: groovyx.net.http.HttpResponseException: Bad Gateway

I had updated to the latest code and deployed V1.2 when it happened last time. But Ring Alarm has has stopped reporting status since yesterday. I did realize that when I logged out and tried to sign back in again from Smartthing App, ring is sending me a verification code although I don't have 2 factor authentication enabled on my Ring acct. Anyway to bypass this ?

**Comment by asishrs** [comment]
@DjAnu check this https://github.com/asishrs/smartthings-ringalarmv2/issues/33

It seems Ring is forcing 2FA on all your accounts. You must either stop the sync or reinstall the app https://github.com/asishrs/smartthings-ringalarmv2/issues/33#issuecomment-590644815 to avoid the issues with your Account. 

I see same issues on the sync part though the Arm/Disarm is working.  I will check this.

**Comment by asishrs** [comment]
In my case Ring refresh token is expired which is surprising as it supposed not to have an expiry. I uninstalled and reinstalled the ST app (which forces to get a new refreshToken) and everything working as expected. Please follow that as a workaround for now. I will update the ST app code to handle this.

**Comment by DjAnu** [comment]
Hey, Thanks for your quick response and support. Looks like it was too late for me to take any action. Ring already locked me out for 24 hours. I spoke with their support and they can't lift the lock which is kind of ridiculous. I wonder what happens if I am actually logged out of Ring App. Only option will be to use Ring Key Pad, very inconvenient. Looks like my only option now is to wait for 24 hours and retry tomorrow.

How would I enter the Authentication code that I'll get from Ring when I sign in again ?

**Comment by DjAnu** [comment]
Sorry spoke too soon. Read the issue #33 Will try again tomorrow since Ring said I'll have to wait for 24 hours, They can't lift the restriction.

**Comment by asishrs** [comment]
Once you select 2FA option on your ST app, you will have an option to enter the code from text message.

**Comment by DjAnu** [comment]
I was finally able to install latest app and devices and connect it with ring acct, however I realized that latest app sync it with modes as opposed to SHM state. How can I make it sync with SHM state only and ignore the modes ? I don’t want to assign modes based on SHM status.

**Comment by asishrs** [comment]
You can use webcore to sync with SHM status. The ST app doesn’t support that natively. If you don’t want to use status change based on modes, you can uncheck all the options on mode sections on `Alarm Monitoring`

**Comment by DjAnu** [comment]
I use Rule Machine for all automation, I am not sure if i can sync status of Ring Alarm and SHM using Rule machine. Surprisingly It was working perfectly fine until I just updated the APP. I think I used Ring Alarm State App in the past to sync the state which is syncing even now but right after that sync something puts back the Ring Alarm to off state, I am not sure what is causing that.

**Comment by adessmith** [comment]
> but right after that sync something puts back the Ring Alarm to off state, I am not sure what is causing that.

This sounds like the same problem I am experiencing here
https://github.com/asishrs/smartthings-ringalarmv2/issues/34

I updated from V2 to V3, now when ST tells my alarm to arm, it appears armed in ST although it never actually arms. Then when the next polling cycle occurs (mine is set to 1 minute) it says it was turned back off.

**Comment by DjAnu** [comment]
I had set up mine with V2 as well and it was working fine. I forgot what i used to sync the status. What are you using with V3 to sync as there seem to be no option to sync with SHM status in V3 only option is to go with Mode. 

I used Ring Alarm State App.

> > but right after that sync something puts back the Ring Alarm to off state, I am not sure what is causing that.
> 
> This sounds like the same problem I am experiencing here
> #34
> 
> I updated from V2 to V3, now when ST tells my alarm to arm, it appears armed in ST although it never actually arms. Then when the next polling cycle occurs (mine is set to 1 minute) it says it was turned back off.

**Comment by DjAnu** [comment]
Where can I find the code for Ring Smart APP V2 and V1 ? I can't seem to see it on the github ?

**Comment by DjAnu** [comment]
Asish, I saw that in your V3 app code you have setAlarmModeBasedOnSHMTrigger, Does it work as it should ? Can I expect this to sync the status with SHM ?

**Comment by DjAnu** [comment]
BTW I had used this app to sync with SHM.

https://community.smartthings.com/t/ring-alarm-released-integration-project-in-post-13/128449/105

**Comment by rickscherer** [comment]
@asishrs I see that your latest SmartApp does have the shmHandler watching in it but it is commented out... were you having problems implementing? I'd really hate to install webCoRE just for shm+ring syncing.

**Comment by DjAnu** [comment]
> You can use webcore to sync with SHM status. The ST app doesn’t support that natively. If you don’t want to use status change based on modes, you can uncheck all the options on mode sections on `Alarm Monitoring`

Hi Asish, I finally installed Webcore and I am really liking it. It seem to have more options compared to RuleMachine. Has anyone created a piston to sync SHM-Ring Alarm both ways. I have created 3 pistons to change Ring Alarm state when SHM state changes. It seem tedious but is working for now.
