### ISSUE TITLE
shm sync feature request

### ISSUE THREAD

**Issue by rickscherer** [asishrs/smartthings-ringalarmv2#37]
@asishrs I see that your latest v3 SmartApp does have the shmHandler watching in it but it is commented out... were you having problems implementing? I'd really hate to install webCoRE just for shm+ring syncing.

**Comment by asishrs** [comment]
SHM was present in older versions but I disabled that in favor of `mode`s. Did you try using the `mode` for automation?

**Comment by rickscherer** [comment]
I do have it configured for setting Away mode.  I'm just being selfish as I have other things tied to SHM that I'd like to continue to use, however with some modifications I should be able to use `mode` just fine.
