### ISSUE TITLE
new SmartThings app display issue

### ISSUE THREAD

**Issue by alejandro2892** [asishrs/smartthings-ringalarmv2#38]
Hi,

On the new SmartThings app is not showing the off/home/away; instead it is showing Off/ Strobe/ Siren and Strobe/ Siren
![Screenshot_20200306-093917_SmartThings](https://user-images.githubusercontent.com/47607785/76094163-1fb36000-5f90-11ea-8f68-53e67eede6bd.jpg)

**Comment by asishrs** [comment]
At present, this doesn't support in new ST app. I will update this in sometime.
