### ISSUE TITLE
Integration died today

### ISSUE THREAD

**Issue by ampersandru** [asishrs/smartthings-ringalarmv2#39]
My integration died the past 24 hours - looking at my AWS dashboard, the calls went to 0 and the errors went high. I removed all buckets and stacks and recreated it. Removed the smartapp and created a new one, wntered new api details into the smartapp, and while ZID and location shows up, theres no alarm for me to selection in the Alarm Monitoring section. It just says "You cant currently add this." Anyone else experiencing this?

**Comment by ampersandru** [comment]
Edit, sorry, after removing the entire ring devices from ST, I forgot to readd the device - all working now!

Any idea why it stopped working in the first place?

**Comment by asishrs** [comment]
This happened in the past for me as well. I suspect this is due to invalidation of token. I started a fix for this, yet to finish that.
