### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by kesjam** [asishrs/smartthings-ringalarmv2#4]
Thank you for this tutorial! I followed all of the steps and stuck on: Test Lambda and Get Ring Location Id and ZID.  

1. Test Lambda: I don't know how to use Lambda or where to enter the POST info you instructed
2.Get Ring Location Id and ZID:  Can you make a visual screenshot of where this info is? I keep hunting but I must be doing it wrong and lost.  I am unsure of where to look or what to do here.  I cant locate the info.

Awaiting your response so I can finish set up :)
Jamie

**Comment by wrymer876** [comment]
I am in the same spot and need a life line, please help.

**Comment by mhatrey** [comment]
@kesjam & @wrymer876 

> 1. Test Lambda: I don't know how to use Lambda or where to enter the POST info you instructed

To test the Lambda function, @asishrs  is asking to use Terminal (natively available in Mac & Linux). *Sorry I'm windows illiterate*, but quick googles shows that there is a cURL for Windows available that you can use to test this - http://www.confusedbycode.com/curl/

However, easier way would be to hop on to Chrome browser and install a [Restful Client](https://chrome.google.com/webstore/detail/restlet-client-rest-api-t/aejoelaoggembcahagimdiliamlcdmfm?hl=en-US) extension and execute this. 

The below image should help 
![Imgur](https://i.imgur.com/cwy40PW.jpg)

> 2.Get Ring Location Id and ZID:  Can you make a visual screenshot of where this info is? I keep hunting but I must be doing it wrong and lost.  I am unsure of where to look or what to do here.  I cant locate the info.

If you able to execute the Test function, this is pretty much not needed as the `meta` call returns location & ZID.

**Comment by asishrs** [comment]
Thanks @mhatrey ! @kesjam @wrymer876 You can use software like https://www.getpostman.com/ to test using a GUI.
