### ISSUE TITLE
Alarm will not disarm

### ISSUE THREAD

**Issue by chickok77** [asishrs/smartthings-ringalarmv2#46]
I recently redid the entire installation for version 3.4. When I select Armed (away) or Armed (stay) on the smart things classic app, it triggers the Ring alarm to successfully go to Away or Home mode respectively. However, When I choose Disarmed on the ST app, it does not disarm the Ring alarm. If I click "Off" in the ST  Ring app, it says "Off Pending", but never disarms the alarm. Any ideas?

**Comment by chickok77** [comment]
Device Logs from Lambda

2020-05-15

20:43:14
START RequestId: c70d68c3-d953-44a5-82d3-a73229242c4e Version: $LATEST

20:43:14
Ring Alarm - Version 3.4.0

20:43:14
Requested Action - devices

20:43:14
Location ID fa7a6d2c-054c-4ad4-8592-12f5d61fe762

20:43:14
Connection [ec2-34-201-1-213.prd.rings.solutions, d0c7cd1f-cfb2-497f-982f-e9bdc1d84138]

20:43:17
Timeout after 3 seconds

20:43:17
read: read tcp 169.254.76.1:38252->34.201.1.213:443: use of closed network connection

20:43:17
Raw Device

20:43:17
&{DeviceInfoDocGetList DeviceInfoDocType 1 22416105-20f2-407c-877b-c88bbef0be84 [{{{zigbee 0 none 0a09b101-e45f-4594-acb5-2ddaad3d0f8b ok {{false} {false}} 1516377079414 adapter.zigbee 0 1582103614312 zigbee ZigBee onboard adapter 0 1 complete unset 0 [hidden unremovable] ok 6eb04d18-4e9a-49ee-8a04-d5614aab1423 }} {{0 0 false }} {{20 796 false }} {[]}} {{{none 0 none ok {{false} {false}} 15163770

20:43:17
END RequestId: c70d68c3-d953-44a5-82d3-a73229242c4e

20:43:17
REPORT RequestId: c70d68c3-d953-44a5-82d3-a73229242c4e Duration: 3176.06 ms Billed Duration: 3200 ms Memory Size: 512 MB Max Memory Used: 47 MB

**Comment by asishrs** [comment]
can you look into the ST logs as well and see if the action is triggering a Lambda call?

**Comment by hvyarms** [comment]
6:01:07 PM: debug setAlarmModeBasedOnModeTrigger() -> No actions set for location mode Alarm-Disarmed or Ring Alarm Device already set to off - aborting
 6:01:07 PM: debug setAlarmModeBasedOnModeTrigger() -> Current alarm state is: off
 6:01:07 PM: debug setAlarmModeBasedOnModeTrigger() -> Setting Ring Alarm mode Ring Alarm Device
 6:01:07 PM: debug modeaction() -> Alarm-Disarmed
 6:00:56 PM: debug Ring Alarm is Armed HOME
 6:00:56 PM: debug send() -> sending push message
 6:00:56 PM: info setalarmhome() -> Ring Alarm is Armed HOME
 6:00:56 PM: trace ringApiCall() -> Ring Alarm HOME response data: [message:Success]
 6:00:55 PM: info ringApiCall() -> Calling AWS API for Ring Alarm with route `home`. API Call ready - true
 6:00:55 PM: trace ringGetAccessAndRefreshToken() -> Request for Access Token Successful.
 6:00:55 PM: debug setAlarmModeBasedOnModeTrigger() -> Location mode: Alarm-Home
 6:00:55 PM: debug setAlarmModeBasedOnModeTrigger() -> Current alarm state is: off
 6:00:55 PM: debug setAlarmModeBasedOnModeTrigger() -> Setting Ring Alarm mode Ring Alarm Device
 6:00:55 PM: debug modeaction() -> Alarm-Home

**Comment by hvyarms** [comment]
Seems to abort triggering the lambda call because the current alarm state is reporting as off incorrectly.

**Comment by hvyarms** [comment]
As a hacky work around until we can fix the status calls you can get disarm working by making this change to the smart app code and updating.  This worked for me and I can arm / disarm now.  Keep in mind you are bypassing the state check so it might cause some lambda error if you try to disarm when already disarmed.

**In this block:** 
_def setAlarmModeBasedOnModeTrigger() {_
**change this line:**
_if(state.locationmode in modealarmoff && state.alarmstate !="off") {_
**to:**
_if(state.locationmode in modealarmoff) {_
