### ISSUE TITLE
Got it working - Status of smart door locks not showing - Can you help?

### ISSUE THREAD

**Issue by sksilver** [asishrs/smartthings-ringalarmv2#49]
Hello,

I did get it working and I love it. It pulled over all my security devices but it did not pull over my door lock status. I have 3 schlage door locks.

Would you know how I can get that to show status as well in smartthings?

Thank you,

nyscooter

**Comment by asishrs** [comment]
That’s great to hear. The current version of app doesn’t support door locks. Also some users reported that the automation doesn’t work well with ring accounts with door locks.

**Comment by sksilver** [comment]
Is it possible to just provide the ability to show whether the device is unlocked or locked.

Don't need to control it, just want status.

Is that possible?

**Comment by sksilver** [comment]
Is it possible to create a version of code, where in smart things, I would just see the status of locked or unlocked?

**Comment by asishrs** [comment]
Ring doesn’t have apis for understanding how these devices are behaving. Without that it will be difficult to create a device type for locks.

**Comment by sksilver** [comment]
So there is no way to tap into this status page? The locks are registered
to ring security hub direct through zwave ?

**Comment by asishrs** [comment]
Unfortunately no 😢

**Comment by sksilver** [comment]
If there is ever an opportunity to allow to tap into it and you need a test
subject, count me in

**Comment by asishrs** [comment]
With the migration to the new ST app, there is not much option left with this integration. If ever, I am going to look into this, I will let you know.
