### ISSUE TITLE
CURL testing

### ISSUE THREAD

**Issue by yieldhog** [asishrs/smartthings-ringalarmv2#5]
Hi -- I have tried and deleted the process a few times, when I walk through the AWS deployment and get to the testing stage, when I invoke the following command:

curl -X POST \
    {https://XXXX.execute-api.us-east-1.amazonaws.com/default}/meta \
    -H 'x-api-key: XXXX' \
    -d '{
    "user": “my@email.com”,
    "password" : “XXXX”
  }'

I receive "message":"Forbidden" as the result. Any help appreciated, I am positive the username/password are correct.

**Comment by kesjam** [comment]
I am getting forbidden 403 errors as well. 

<img width="961" alt="screenshot at mar 05 13-19-39" src="https://user-images.githubusercontent.com/18688471/53827748-d62dd080-3f49-11e9-8a0a-8caae15cf9f8.png">

**Comment by asishrs** [comment]
@kesjam you are missing the deployment stage name in the url, usually its `default `

**Comment by asishrs** [comment]
@seasideCT I see an extra `{}` on the curl request. can you remove that and try? You need to replace `{Invoke URL From Above}` with your url.
```
curl -X POST 
https://XXXX.execute-api.us-east-1.amazonaws.com/default/meta 
-H 'x-api-key: XXXX' 
-d '{
"user": “my@email.com”,
"password" : “XXXX”
}'
```
