### ISSUE TITLE
SmartThings App Migration

### ISSUE THREAD

**Issue by GizmoGoody** [asishrs/smartthings-ringalarmv2#53]
@asishrs I just started receiving the notices to migrate to the new app. So, I figured I should check out my Ring Alarm device in the new app. It gave me this screenshot. I tapped cancel concerned it would break the custom integration. What do you think?
![4277D501-9893-4C86-8312-897712632B04](https://user-images.githubusercontent.com/46235745/89224215-f1f93400-d58c-11ea-89c9-dd40d7a1b0f0.png)

**Comment by asishrs** [comment]
I tried to migrate mine as well. The way new ST app works is different and I need to make some fundamental changes to the DH. It is not working as expected in the new app.

**Comment by Its2loud1** [comment]
Hi Asish,

Are you planning on getting this integration to work in the new app?  Currently we cannot arm Hone or arm Stay I. The new app or link it to STHM.

Thanks for all the work you do with this integration.

**Comment by asishrs** [comment]
I checked this few weeks back, and based on what I read, it is not possible. The new app doesn't allow custom controls.

**Comment by Its2loud1** [comment]
> I checked this few weeks back, and based on what I read, it is not possible. The new app doesn't allow custom controls.

Really!?  Ugh. That stinks. So stupid of them. Would it work if we used STHM in the new app?

So does that mean this will be dead in the water in the coming months?

**Comment by asishrs** [comment]
I am thinking to convert the app as Switch Type so that I can try to have 3 opinions on that. I will give a shot on this soon.

**Comment by Its2loud1** [comment]
> I am thinking to convert the app as Switch Type so that I can try to have 3 opinions on that. I will give a shot on this soon.

Oh! I can see how that might work if it’s a fan switch type maybe.  You’re the expert. Thanks for taking a look!

**Comment by aditiArun05** [comment]
Thanks for trying
