### ISSUE TITLE
Status not showing in New Smart things app

### ISSUE THREAD

**Issue by sksilver** [asishrs/smartthings-ringalarmv2#55]
Hello,

I had an issue over the weekend. I have to remove the ring devices from my smart things app then re-add it. Now status is showing for the firealarm, but is not showing for the motion sensors and the window sensors.

But it does show in the orginal smart things app.

Any thoughts on why this would happen and how to fix?

Thank you,

Scott

**Comment by asishrs** [comment]
There are several things changes in ST new app last few weeks. I need to revisit the setup to understand how to fix those 😢
