### ISSUE TITLE
New ST App

### ISSUE THREAD

**Issue by broyuken** [asishrs/smartthings-ringalarmv2#6]
I tried using the new app the other day and the alarm was all messed up. The only options were like disarmed, lights, and siren or something along those lines. Not sure if it’s something ST needs to fix or something on your end, just bringing attention to it.

**Comment by asishrs** [comment]
that's strange. can you post a picture of your smartapp? if you have time to reinstall the app, I will recommend that as well. Also, you need to set the device count on the handler code, check this https://github.com/asishrs/smartthings-ringalarmv2#arrow_up-update-device-handler

**Comment by broyuken** [comment]
https://m.imgur.com/a/HS7jYVN

Here's a screenshot. The icon for it on the home screen is a contact sensor as well. Everything is on the v2 version of the app, updated the device handler with the correct info. It all works great in the classic app, not so much in the new one.

**Comment by asishrs** [comment]
Thanks for sharing this! The app currently works only in classic version. I haven’t explored the new app part. Sorry it’s disappointing for you.

**Comment by arjunrbery** [comment]
Hey @asishrs,

I'm having the same issue. I noticed that if I test it from the Graph site it works fine. Also, if I play around with the naming, I can still get the off button to work.

Thanks!

**Comment by asishrs** [comment]
Unfortunately, I don’t have enough experience with the new ST app. If anyone wants to use the code and try to rewrite in the newer version, please feel free.
