### ISSUE TITLE
Internal Server Error/Bad Gateway

### ISSUE THREAD

**Issue by mbhforum** [asishrs/smartthings-ringalarmv2#7]
In the Smartthings IDE Logs, I get the below error:
Ring Alarm Status check Error: groovyx.net.http.HttpResponseException: Bad Gateway

I can set the state fine (Off, Home or Away), but polling doesn't work. When I try to run the status command via Curl, I get an "Internal Server Error".  I can run Curl commands for /off, /home, /away fine. 

Any ideas?

**Comment by asishrs** [comment]
Can you share the output of status curl command ?

**Comment by mbhforum** [comment]
Internal Server Error (off the top of my head).

**Comment by asishrs** [comment]
were you able to get pass this?

**Comment by mbhforum** [comment]
Unfortunately not.

**Comment by asishrs** [comment]
I can take a look if you can share the `curl` request/response. Please remove any sensitive information before you post.

**Comment by mbhforum** [comment]
Sure.  Here is the error: (I removed all of my sensitive information and replaced with LEFTBLANK)

curl -X POST https://LEFTBLANK.execute-api.us-east-1.amazonaws.com/default/status -H 'x-api-key: LEFTBLANK   -d '{"user": "LEFTBLANK","password" : "LEFTBLANK"}'
{"message": "Internal server error"}

**Comment by asishrs** [comment]
Can you verify the API from the AWS console by following below?

- https://console.aws.amazon.com/apigateway/home?region=us-east-1#/apis
- Select the API from the list on the left had side
- Select `Resources` and then select the `/{ring-action+}`
- Choose `ANY` under `/{ring-action+}` and select `Test`
- Select below values 
   - Method: `POST`
   - Path: `status`
   - Headers: `x-api-key:your_api_key`
   - Request Body
  ```
  {
	"user": "your_user_name",
	"password" : "your_password"
  }
  ```

**Comment by mbhforum** [comment]
Here is the error now (I jumbled some of the numbers around, although I don't think they were sensitive):

Sat Apr 13 10:12:43 UTC 2019 : Sending request to https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/arn:aws:lambda:us-east-1:777776666666666:function:Ring-Alarm/invocations
Sat Apr 13 10:12:43 UTC 2019 : Received response. Status: 200, Integration latency: 25 ms
Sat Apr 13 10:12:43 UTC 2019 : Endpoint response headers: {Date=Sat, 13 Apr 2019 10:12:43 GMT, Content-Type=application/json, Content-Length=88, Connection=keep-alive, x-amzn-RequestId=68efc82c-49hggg3, x-amzn-Remapped-Content-Length=0, X-Amz-Executed-Version=$LATEST, X-Amzn-Trace-Id=root=1-5cb1bghghdhdhgheb0684f17;sampled=0}
Sat Apr 13 10:12:43 UTC 2019 : Endpoint response body before transformations: {"statusCode":422,"headers":null,"multiValueHeaders":null,"body":"Unprocessable Entity"}
Sat Apr 13 10:12:43 UTC 2019 : Method response body after transformations: Unprocessable Entity
Sat Apr 13 10:12:43 UTC 2019 : Method response headers: {X-Amzn-Trace-Id=Root=1-5cb1b61b-1e78ddfffhf17;Sampled=0}
Sat Apr 13 10:12:43 UTC 2019 : Successfully completed execution
Sat Apr 13 10:12:43 UTC 2019 : Method completed with status: 422

**Comment by asishrs** [comment]
Looks like the `Request Body` was not proper. Can you check that?

**Comment by mbhforum** [comment]
I copied and pasted the syntax you wrote above. Can you clarify what I might be missing?

**Comment by asishrs** [comment]
can you confirm that you are using v2 of the application (Go implementation of the API)?

**Comment by mbhforum** [comment]
Yes, using v2

**Comment by asishrs** [comment]
At this point, I have no idea about this. Would you mind setting this up once again from scratch? I know its a pain.. :(

**Comment by sfroth** [comment]
Sorry to reopen an old question, but I'm having the same issue. I set up my integration in February, and everything worked then. But now, when I try to call `status` or `meta` via cURL, I get `{"message": "Internal server error"}`. I'm still able to run `off`, `home`, and `away`, and `meta` only works if I pass in the locationId and zid.

Here's my response from test of status, as you requested above:

```Mon Jun 10 15:40:10 UTC 2019 : Starting execution for request: BLANKED
Mon Jun 10 15:40:10 UTC 2019 : HTTP Method: POST, Resource Path: /status
Mon Jun 10 15:40:10 UTC 2019 : Method request path: {ring-action=status}
Mon Jun 10 15:40:10 UTC 2019 : Method request query string: {}
Mon Jun 10 15:40:10 UTC 2019 : Method request headers: {x-api-key=BLANKED}
Mon Jun 10 15:40:10 UTC 2019 : Method request body before transformations: {
    "user": "BLANKED",
    "password" : "BLANKED",
    "locationId" : "BLANKED",
    "zid" : "BLANKED"
  }
Mon Jun 10 15:40:10 UTC 2019 : Endpoint request URI: https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/arn:aws:lambda:us-east-1:BLANKED:function:Ring-Alarm/invocations
Mon Jun 10 15:40:10 UTC 2019 : Endpoint request headers: {x-amzn-lambda-integration-tag=BLANKED, Authorization=*[TRUNCATED], X-Amz-Date=20190610T154010Z, x-amzn-apigateway-api-id=BLANKED, X-Amz-Source-Arn=arn:aws:execute-api:us-east-1:BLANKED:BLANKED/test-invoke-stage/POST/{ring-action+}, Accept=application/json, User-Agent=AmazonAPIGateway_BLANKED, X-Amz-Security-Token= [TRUNCATED]
Mon Jun 10 15:40:10 UTC 2019 : Endpoint request body after transformations: {"resource":"/{ring-action+}","path":"/status","httpMethod":"POST","headers":{"x-api-key":" BLANKED"},"multiValueHeaders":{"x-api-key":[" BLANKED"]},"queryStringParameters":null,"multiValueQueryStringParameters":null,"pathParameters":{"ring-action":"status"},"stageVariables":null,"requestContext":{"path":"/{ring-action+}","accountId":"BLANKED","resourceId":"BLANKED","stage":"test-invoke-stage","domainPrefix":"testPrefix","requestId":"BLANKED","identity":{"cognitoIdentityPoolId":null,"cognitoIdentityId":null,"apiKey":"test-invoke-api-key","principalOrgId":null,"cognitoAuthenticationType":null,"userArn":"arn:aws:iam::BLANKED:root","apiKeyId":"test-invoke-api-key-id","userAgent":"aws-internal/3 aws-sdk-java/1.11.534 Linux/4.9.137-0.1.ac.218.74.329.metal1.x86_64 OpenJDK_64-Bit_Server_VM/25.202-b08 java/1.8.0_202 vendor/Oracle_Corporation","accountId":"BLANKED"," [TRUNCATED]
Mon Jun 10 15:40:10 UTC 2019 : Sending request to https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/arn:aws:lambda:us-east-1:BLANKED:function:Ring-Alarm/invocations
Mon Jun 10 15:40:14 UTC 2019 : Received response. Status: 200, Integration latency: 3652 ms
Mon Jun 10 15:40:14 UTC 2019 : Endpoint response headers: {Date=Mon, 10 Jun 2019 15:40:14 GMT, Content-Type=application/json, Content-Length=107, Connection=keep-alive, x-amzn-RequestId=BLANKED, X-Amz-Function-Error=Unhandled, x-amzn-Remapped-Content-Length=0, X-Amz-Executed-Version=$LATEST, X-Amzn-Trace-Id=root=BLANKED;sampled=0}
Mon Jun 10 15:40:14 UTC 2019 : Endpoint response body before transformations: {"errorMessage":"RequestId: BLANKED Process exited before completing request"}
Mon Jun 10 15:40:14 UTC 2019 : Lambda execution failed with status 200 due to customer function error: RequestId: BLANKED Process exited before completing request. Lambda request id: BLANKED
Mon Jun 10 15:40:14 UTC 2019 : Method completed with status: 502```
