### ISSUE TITLE
Ring to ST communication

### ISSUE THREAD

**Issue by chickok77** [asishrs/smartthings-ringalarmv2#8]
Thanks so much for doing the leg work to get this going! I was able to successfully get the integration all working. however, I have a question about Ring to ST communication. Is there a way in ST classic app to arm the ST home automation when the Ring alarm is armed? If I try an automation, the only options under “Something opens or closes” for my ring ST are open/close/opens or closes. Is there a way in the automations to select the ring ST mode itself? Thanks in advance.

**Comment by asishrs** [comment]
You can set up a virtual switch in ST and have that act as a bridge between Ring Alarm and ST or use WebCORE https://github.com/asishrs/smartthings-ringalarmv2#integration-with-webcore

**Comment by chickok77** [comment]
I have used the IFTTT, but have not seen how to get the “state” of the ring alarm in ST. When I try to set up an automation, the only states are open/closed (for the ring contact sensor) and the alarm states (siren, strobe, etc). Is there a way to get the “armed home, armed away, off” state in ST?

**Comment by chickok77** [comment]
Also, I looked at the webcore code, but, having limited experience with it, where would I put that code? Into the ST website?

**Comment by asishrs** [comment]
You can start from here https://wiki.webcore.co/

**Comment by chickok77** [comment]
Thanks. I’d like to understand the inner workings of the code so that it’s customizable. It looks like I just install webcore than then add the listed code as a piston?

**Comment by asishrs** [comment]
you can check the whole code in this repo, let me know if you have any questions.

**Comment by chickok77** [comment]
I got it to work using the statuses of 'home' 'away' and 'off', for future noobs like me.
